// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (actor_user_id, action, target_type, target_id, request_id, detail)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, actor_user_id, action, target_type, target_id, request_id, detail, created_at
`

type CreateAuditEventParams struct {
	ActorUserID *uuid.UUID `json:"actor_user_id"`
	Action      string     `json:"action"`
	TargetType  string     `json:"target_type"`
	TargetID    *string    `json:"target_id"`
	RequestID   *string    `json:"request_id"`
	Detail      []byte     `json:"detail"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.Detail,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.RequestID,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredContent = `-- name: DeleteExpiredContent :execrows
DELETE FROM content_records WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredContent(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredContent)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContentRecord = `-- name: GetContentRecord :one
SELECT request_id, encrypted_content, expires_at, created_at FROM content_records WHERE request_id = $1 AND expires_at > now()
`

func (q *Queries) GetContentRecord(ctx context.Context, requestID uuid.UUID) (ContentRecord, error) {
	row := q.db.QueryRow(ctx, getContentRecord, requestID)
	var i ContentRecord
	err := row.Scan(
		&i.RequestID,
		&i.EncryptedContent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, action, target_type, target_id, request_id, detail, created_at FROM audit_events ORDER BY created_at DESC, id LIMIT $2 OFFSET $1
`

type ListAuditEventsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContentRecord = `-- name: UpsertContentRecord :exec
INSERT INTO content_records (request_id, encrypted_content, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (request_id) DO UPDATE SET encrypted_content = excluded.encrypted_content, expires_at = excluded.expires_at
`

type UpsertContentRecordParams struct {
	RequestID        uuid.UUID          `json:"request_id"`
	EncryptedContent []byte             `json:"encrypted_content"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertContentRecord(ctx context.Context, arg UpsertContentRecordParams) error {
	_, err := q.db.Exec(ctx, upsertContentRecord, arg.RequestID, arg.EncryptedContent, arg.ExpiresAt)
	return err
}
