// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configuration.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConfigOutbox = `-- name: CreateConfigOutbox :exec
INSERT INTO config_outbox (revision_id, active_version, document)
VALUES ($1, $2, $3)
`

type CreateConfigOutboxParams struct {
	RevisionID    uuid.UUID `json:"revision_id"`
	ActiveVersion int64     `json:"active_version"`
	Document      []byte    `json:"document"`
}

func (q *Queries) CreateConfigOutbox(ctx context.Context, arg CreateConfigOutboxParams) error {
	_, err := q.db.Exec(ctx, createConfigOutbox, arg.RevisionID, arg.ActiveVersion, arg.Document)
	return err
}

const createConfigRevision = `-- name: CreateConfigRevision :one
INSERT INTO config_revisions (document, checksum, created_by)
VALUES ($1, $2, $3) RETURNING id, revision, document, checksum, created_by, created_at, published_at, published_by
`

type CreateConfigRevisionParams struct {
	Document  []byte    `json:"document"`
	Checksum  string    `json:"checksum"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateConfigRevision(ctx context.Context, arg CreateConfigRevisionParams) (ConfigRevision, error) {
	row := q.db.QueryRow(ctx, createConfigRevision, arg.Document, arg.Checksum, arg.CreatedBy)
	var i ConfigRevision
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Document,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const getActiveConfig = `-- name: GetActiveConfig :one
SELECT r.id, r.revision, r.document, r.checksum, r.created_by, r.created_at, r.published_at, r.published_by, a.version AS active_version, a.updated_at AS active_updated_at
FROM active_config a JOIN config_revisions r ON r.id = a.revision_id WHERE a.singleton = true
`

type GetActiveConfigRow struct {
	ID              uuid.UUID          `json:"id"`
	Revision        *int64             `json:"revision"`
	Document        []byte             `json:"document"`
	Checksum        string             `json:"checksum"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	PublishedBy     *uuid.UUID         `json:"published_by"`
	ActiveVersion   int64              `json:"active_version"`
	ActiveUpdatedAt pgtype.Timestamptz `json:"active_updated_at"`
}

func (q *Queries) GetActiveConfig(ctx context.Context) (GetActiveConfigRow, error) {
	row := q.db.QueryRow(ctx, getActiveConfig)
	var i GetActiveConfigRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Document,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.ActiveVersion,
		&i.ActiveUpdatedAt,
	)
	return i, err
}

const getConfigRevision = `-- name: GetConfigRevision :one
SELECT id, revision, document, checksum, created_by, created_at, published_at, published_by FROM config_revisions WHERE id = $1
`

func (q *Queries) GetConfigRevision(ctx context.Context, id uuid.UUID) (ConfigRevision, error) {
	row := q.db.QueryRow(ctx, getConfigRevision, id)
	var i ConfigRevision
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Document,
		&i.Checksum,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const initializeActiveConfig = `-- name: InitializeActiveConfig :execrows
INSERT INTO active_config (singleton, revision_id, version) VALUES (true, $1, 1) ON CONFLICT DO NOTHING
`

func (q *Queries) InitializeActiveConfig(ctx context.Context, revisionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, initializeActiveConfig, revisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConfigRevisions = `-- name: ListConfigRevisions :many
SELECT id, revision, document, checksum, created_by, created_at, published_at, published_by FROM config_revisions ORDER BY revision DESC LIMIT $2 OFFSET $1
`

type ListConfigRevisionsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListConfigRevisions(ctx context.Context, arg ListConfigRevisionsParams) ([]ConfigRevision, error) {
	rows, err := q.db.Query(ctx, listConfigRevisions, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigRevision{}
	for rows.Next() {
		var i ConfigRevision
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.Document,
			&i.Checksum,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.PublishedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingConfigOutbox = `-- name: ListPendingConfigOutbox :many
SELECT id, revision_id, active_version, document, attempts, last_error, delivered_at, created_at FROM config_outbox WHERE delivered_at IS NULL ORDER BY id LIMIT $1
`

func (q *Queries) ListPendingConfigOutbox(ctx context.Context, batchSize int32) ([]ConfigOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingConfigOutbox, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigOutbox{}
	for rows.Next() {
		var i ConfigOutbox
		if err := rows.Scan(
			&i.ID,
			&i.RevisionID,
			&i.ActiveVersion,
			&i.Document,
			&i.Attempts,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveConfig = `-- name: LockActiveConfig :one
SELECT revision_id, version FROM active_config WHERE singleton = true FOR UPDATE
`

type LockActiveConfigRow struct {
	RevisionID uuid.UUID `json:"revision_id"`
	Version    int64     `json:"version"`
}

func (q *Queries) LockActiveConfig(ctx context.Context) (LockActiveConfigRow, error) {
	row := q.db.QueryRow(ctx, lockActiveConfig)
	var i LockActiveConfigRow
	err := row.Scan(&i.RevisionID, &i.Version)
	return i, err
}

const markConfigOutboxDelivered = `-- name: MarkConfigOutboxDelivered :exec
UPDATE config_outbox SET delivered_at = now(), attempts = attempts + 1, last_error = NULL WHERE id = $1
`

func (q *Queries) MarkConfigOutboxDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markConfigOutboxDelivered, id)
	return err
}

const markConfigOutboxFailed = `-- name: MarkConfigOutboxFailed :exec
UPDATE config_outbox SET attempts = attempts + 1, last_error = $1 WHERE id = $2
`

type MarkConfigOutboxFailedParams struct {
	LastError *string `json:"last_error"`
	ID        int64   `json:"id"`
}

func (q *Queries) MarkConfigOutboxFailed(ctx context.Context, arg MarkConfigOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markConfigOutboxFailed, arg.LastError, arg.ID)
	return err
}

const markConfigPublished = `-- name: MarkConfigPublished :exec
UPDATE config_revisions SET published_at = now(), published_by = $1 WHERE id = $2
`

type MarkConfigPublishedParams struct {
	PublishedBy *uuid.UUID `json:"published_by"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) MarkConfigPublished(ctx context.Context, arg MarkConfigPublishedParams) error {
	_, err := q.db.Exec(ctx, markConfigPublished, arg.PublishedBy, arg.ID)
	return err
}

const publishConfigRevision = `-- name: PublishConfigRevision :execrows
UPDATE active_config SET revision_id = $1, version = version + 1, updated_at = now()
WHERE singleton = true AND version = $2
`

type PublishConfigRevisionParams struct {
	RevisionID      uuid.UUID `json:"revision_id"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) PublishConfigRevision(ctx context.Context, arg PublishConfigRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishConfigRevision, arg.RevisionID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
