// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindGatewayKeyModel = `-- name: BindGatewayKeyModel :exec
INSERT INTO gateway_key_models (gateway_key_id, model_id) VALUES ($1, $2)
`

type BindGatewayKeyModelParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	ModelID      uuid.UUID `json:"model_id"`
}

func (q *Queries) BindGatewayKeyModel(ctx context.Context, arg BindGatewayKeyModelParams) error {
	_, err := q.db.Exec(ctx, bindGatewayKeyModel, arg.GatewayKeyID, arg.ModelID)
	return err
}

const claimGatewayKeyMutation = `-- name: ClaimGatewayKeyMutation :one
INSERT INTO gateway_key_mutations (actor_user_id, idempotency_key, request_fingerprint, request_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (actor_user_id, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, idempotency_key, request_fingerprint, request_id, gateway_key_id, result, created_at
`

type ClaimGatewayKeyMutationParams struct {
	ActorUserID        uuid.UUID `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID `json:"idempotency_key"`
	RequestFingerprint []byte    `json:"request_fingerprint"`
	RequestID          string    `json:"request_id"`
}

func (q *Queries) ClaimGatewayKeyMutation(ctx context.Context, arg ClaimGatewayKeyMutationParams) (GatewayKeyMutation, error) {
	row := q.db.QueryRow(ctx, claimGatewayKeyMutation,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.RequestID,
	)
	var i GatewayKeyMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.GatewayKeyID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const claimMemberMutation = `-- name: ClaimMemberMutation :one
INSERT INTO member_mutations (actor_user_id, action, idempotency_key, user_id, request_fingerprint, request_id, encrypted_one_time_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (actor_user_id, action, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, action, idempotency_key, user_id, request_fingerprint, request_id, encrypted_one_time_secret, result, created_at
`

type ClaimMemberMutationParams struct {
	ActorUserID            uuid.UUID  `json:"actor_user_id"`
	Action                 string     `json:"action"`
	IdempotencyKey         uuid.UUID  `json:"idempotency_key"`
	UserID                 *uuid.UUID `json:"user_id"`
	RequestFingerprint     []byte     `json:"request_fingerprint"`
	RequestID              string     `json:"request_id"`
	EncryptedOneTimeSecret []byte     `json:"encrypted_one_time_secret"`
}

func (q *Queries) ClaimMemberMutation(ctx context.Context, arg ClaimMemberMutationParams) (MemberMutation, error) {
	row := q.db.QueryRow(ctx, claimMemberMutation,
		arg.ActorUserID,
		arg.Action,
		arg.IdempotencyKey,
		arg.UserID,
		arg.RequestFingerprint,
		arg.RequestID,
		arg.EncryptedOneTimeSecret,
	)
	var i MemberMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.EncryptedOneTimeSecret,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeGatewayKeyMutation = `-- name: CompleteGatewayKeyMutation :one
UPDATE gateway_key_mutations SET gateway_key_id = $1, result = $2
WHERE id = $3 RETURNING id, actor_user_id, idempotency_key, request_fingerprint, request_id, gateway_key_id, result, created_at
`

type CompleteGatewayKeyMutationParams struct {
	GatewayKeyID *uuid.UUID `json:"gateway_key_id"`
	Result       []byte     `json:"result"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) CompleteGatewayKeyMutation(ctx context.Context, arg CompleteGatewayKeyMutationParams) (GatewayKeyMutation, error) {
	row := q.db.QueryRow(ctx, completeGatewayKeyMutation, arg.GatewayKeyID, arg.Result, arg.ID)
	var i GatewayKeyMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.GatewayKeyID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeMemberMutation = `-- name: CompleteMemberMutation :one
UPDATE member_mutations
SET user_id = $1, result = $2
WHERE id = $3
RETURNING id, actor_user_id, action, idempotency_key, user_id, request_fingerprint, request_id, encrypted_one_time_secret, result, created_at
`

type CompleteMemberMutationParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Result []byte     `json:"result"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) CompleteMemberMutation(ctx context.Context, arg CompleteMemberMutationParams) (MemberMutation, error) {
	row := q.db.QueryRow(ctx, completeMemberMutation, arg.UserID, arg.Result, arg.ID)
	var i MemberMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.EncryptedOneTimeSecret,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE status <> 'deleted'
  AND ($1::user_status IS NULL OR status = $1)
  AND ($2::text = '' OR concat_ws(' ', email, display_name) ILIKE '%' || $2::text || '%')
`

type CountUsersParams struct {
	Status *UserStatus `json:"status"`
	Search string      `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGatewayKey = `-- name: CreateGatewayKey :one
INSERT INTO gateway_keys (user_id, name, prefix, secret_digest, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, secret_digest, expires_at, revoked_at, last_used_at, created_at
`

type CreateGatewayKeyParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGatewayKey(ctx context.Context, arg CreateGatewayKeyParams) (GatewayKey, error) {
	row := q.db.QueryRow(ctx, createGatewayKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.SecretDigest,
		arg.ExpiresAt,
	)
	var i GatewayKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_digest, csrf_digest, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_digest, csrf_digest, expires_at, revoked_at, last_seen_at, created_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, role, status)
VALUES (lower($1), $2, $3, $4, $5)
RETURNING id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string     `json:"email"`
	DisplayName  string     `json:"display_name"`
	PasswordHash string     `json:"password_hash"`
	Role         UserRole   `json:"role"`
	Status       UserStatus `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '1 day' OR revoked_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGatewayKeyByDigest = `-- name: GetGatewayKeyByDigest :one
SELECT key.id, key.user_id, key.name, key.prefix, key.secret_digest, key.expires_at, key.revoked_at, key.last_used_at, key.created_at, member.status AS user_status, member.role AS user_role
FROM gateway_keys key JOIN users member ON member.id = key.user_id
WHERE key.secret_digest = $1 AND key.revoked_at IS NULL
  AND (key.expires_at IS NULL OR key.expires_at > now())
`

type GetGatewayKeyByDigestRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserStatus   UserStatus         `json:"user_status"`
	UserRole     UserRole           `json:"user_role"`
}

func (q *Queries) GetGatewayKeyByDigest(ctx context.Context, secretDigest []byte) (GetGatewayKeyByDigestRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyByDigest, secretDigest)
	var i GetGatewayKeyByDigestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UserStatus,
		&i.UserRole,
	)
	return i, err
}

const getGatewayKeyForReplacement = `-- name: GetGatewayKeyForReplacement :one
SELECT id, user_id, name, prefix, expires_at, revoked_at, last_used_at, created_at
FROM gateway_keys
WHERE id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
FOR UPDATE
`

type GetGatewayKeyForReplacementRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGatewayKeyForReplacement(ctx context.Context, id uuid.UUID) (GetGatewayKeyForReplacementRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyForReplacement, id)
	var i GetGatewayKeyForReplacementRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGatewayKeyForRevocation = `-- name: GetGatewayKeyForRevocation :one
SELECT id, user_id, revoked_at FROM gateway_keys WHERE id = $1 FOR UPDATE
`

type GetGatewayKeyForRevocationRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetGatewayKeyForRevocation(ctx context.Context, id uuid.UUID) (GetGatewayKeyForRevocationRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyForRevocation, id)
	var i GetGatewayKeyForRevocationRow
	err := row.Scan(&i.ID, &i.UserID, &i.RevokedAt)
	return i, err
}

const getGatewayKeyMutation = `-- name: GetGatewayKeyMutation :one
SELECT id, actor_user_id, idempotency_key, request_fingerprint, request_id, gateway_key_id, result, created_at FROM gateway_key_mutations
WHERE actor_user_id = $1 AND idempotency_key = $2
`

type GetGatewayKeyMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetGatewayKeyMutation(ctx context.Context, arg GetGatewayKeyMutationParams) (GatewayKeyMutation, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyMutation, arg.ActorUserID, arg.IdempotencyKey)
	var i GatewayKeyMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.GatewayKeyID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getGatewayKeyPrincipalByID = `-- name: GetGatewayKeyPrincipalByID :one
SELECT key.id, key.user_id, key.name, key.prefix, key.secret_digest, key.expires_at, key.revoked_at, key.last_used_at, key.created_at, member.status AS user_status, member.role AS user_role
FROM gateway_keys key JOIN users member ON member.id = key.user_id
WHERE key.id = $1 AND key.revoked_at IS NULL
  AND (key.expires_at IS NULL OR key.expires_at > now())
`

type GetGatewayKeyPrincipalByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserStatus   UserStatus         `json:"user_status"`
	UserRole     UserRole           `json:"user_role"`
}

func (q *Queries) GetGatewayKeyPrincipalByID(ctx context.Context, id uuid.UUID) (GetGatewayKeyPrincipalByIDRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyPrincipalByID, id)
	var i GetGatewayKeyPrincipalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UserStatus,
		&i.UserRole,
	)
	return i, err
}

const getGatewayKeyRevocationState = `-- name: GetGatewayKeyRevocationState :one
SELECT user_id, revoked_at FROM gateway_keys WHERE id = $1
`

type GetGatewayKeyRevocationStateRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetGatewayKeyRevocationState(ctx context.Context, id uuid.UUID) (GetGatewayKeyRevocationStateRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyRevocationState, id)
	var i GetGatewayKeyRevocationStateRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const getMemberMutation = `-- name: GetMemberMutation :one
SELECT id, actor_user_id, action, idempotency_key, user_id, request_fingerprint, request_id, encrypted_one_time_secret, result, created_at FROM member_mutations
WHERE actor_user_id = $1 AND action = $2 AND idempotency_key = $3
`

type GetMemberMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Action         string    `json:"action"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetMemberMutation(ctx context.Context, arg GetMemberMutationParams) (MemberMutation, error) {
	row := q.db.QueryRow(ctx, getMemberMutation, arg.ActorUserID, arg.Action, arg.IdempotencyKey)
	var i MemberMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.EncryptedOneTimeSecret,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getModelForGatewayKeyBinding = `-- name: GetModelForGatewayKeyBinding :one
SELECT model.id, model.public_name
FROM models model
WHERE model.id = $1
  AND EXISTS (
    SELECT 1
    FROM subscriptions subscription
    JOIN service_plan_versions version ON version.id = subscription.service_plan_version_id
    JOIN service_plan_version_routes route ON route.service_plan_version_id = version.id AND route.model_id = model.id
    WHERE subscription.user_id = $2
      AND subscription.status = 'active'
      AND subscription.starts_at <= now() AND subscription.expires_at > now()
  )
FOR SHARE
`

type GetModelForGatewayKeyBindingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetModelForGatewayKeyBindingRow struct {
	ID         uuid.UUID `json:"id"`
	PublicName string    `json:"public_name"`
}

func (q *Queries) GetModelForGatewayKeyBinding(ctx context.Context, arg GetModelForGatewayKeyBindingParams) (GetModelForGatewayKeyBindingRow, error) {
	row := q.db.QueryRow(ctx, getModelForGatewayKeyBinding, arg.ID, arg.UserID)
	var i GetModelForGatewayKeyBindingRow
	err := row.Scan(&i.ID, &i.PublicName)
	return i, err
}

const getSessionByDigest = `-- name: GetSessionByDigest :one
SELECT s.id, s.user_id, s.token_digest, s.csrf_digest, s.expires_at, s.revoked_at, s.last_seen_at, s.created_at, u.email, u.display_name, u.role, u.status AS user_status
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_digest = $1 AND s.revoked_at IS NULL AND s.expires_at > now()
`

type GetSessionByDigestRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        UserRole           `json:"role"`
	UserStatus  UserStatus         `json:"user_status"`
}

func (q *Queries) GetSessionByDigest(ctx context.Context, tokenDigest []byte) (GetSessionByDigestRow, error) {
	row := q.db.QueryRow(ctx, getSessionByDigest, tokenDigest)
	var i GetSessionByDigestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.UserStatus,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at FROM users WHERE lower(email) = lower($1) AND status <> 'deleted'
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAdministrativeRecovery = `-- name: GetUserForAdministrativeRecovery :one
SELECT id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForAdministrativeRecovery(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForAdministrativeRecovery, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForGatewayKeyCreation = `-- name: GetUserForGatewayKeyCreation :one
SELECT id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at FROM users WHERE id = $1 AND status = 'active' FOR SHARE
`

func (q *Queries) GetUserForGatewayKeyCreation(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForGatewayKeyCreation, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isBootstrapped = `-- name: IsBootstrapped :one
SELECT CAST(bootstrapped_at IS NOT NULL AS boolean) AS bootstrapped FROM system_state WHERE singleton = true
`

func (q *Queries) IsBootstrapped(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isBootstrapped)
	var bootstrapped bool
	err := row.Scan(&bootstrapped)
	return bootstrapped, err
}

const isGatewayKeyAuthorizedForModel = `-- name: IsGatewayKeyAuthorizedForModel :one
SELECT EXISTS (SELECT 1 FROM gateway_key_models WHERE gateway_key_id = $1 AND model_id = $2)
`

type IsGatewayKeyAuthorizedForModelParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	ModelID      uuid.UUID `json:"model_id"`
}

func (q *Queries) IsGatewayKeyAuthorizedForModel(ctx context.Context, arg IsGatewayKeyAuthorizedForModelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGatewayKeyAuthorizedForModel, arg.GatewayKeyID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGatewayKeyModelBindingsByKey = `-- name: ListGatewayKeyModelBindingsByKey :many
SELECT gkm.model_id, model.public_name
FROM gateway_key_models gkm JOIN models model ON model.id = gkm.model_id
WHERE gkm.gateway_key_id = $1
ORDER BY model.public_name, gkm.model_id
`

type ListGatewayKeyModelBindingsByKeyRow struct {
	ModelID    uuid.UUID `json:"model_id"`
	PublicName string    `json:"public_name"`
}

func (q *Queries) ListGatewayKeyModelBindingsByKey(ctx context.Context, gatewayKeyID uuid.UUID) ([]ListGatewayKeyModelBindingsByKeyRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeyModelBindingsByKey, gatewayKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeyModelBindingsByKeyRow{}
	for rows.Next() {
		var i ListGatewayKeyModelBindingsByKeyRow
		if err := rows.Scan(&i.ModelID, &i.PublicName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayKeyModelBindingsByUser = `-- name: ListGatewayKeyModelBindingsByUser :many
SELECT gkm.gateway_key_id, gkm.model_id, model.public_name
FROM gateway_key_models gkm
JOIN gateway_keys key ON key.id = gkm.gateway_key_id
JOIN models model ON model.id = gkm.model_id
WHERE key.user_id = $1
ORDER BY gkm.gateway_key_id, model.public_name, gkm.model_id
`

type ListGatewayKeyModelBindingsByUserRow struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	ModelID      uuid.UUID `json:"model_id"`
	PublicName   string    `json:"public_name"`
}

func (q *Queries) ListGatewayKeyModelBindingsByUser(ctx context.Context, userID uuid.UUID) ([]ListGatewayKeyModelBindingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeyModelBindingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeyModelBindingsByUserRow{}
	for rows.Next() {
		var i ListGatewayKeyModelBindingsByUserRow
		if err := rows.Scan(&i.GatewayKeyID, &i.ModelID, &i.PublicName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayKeysByUser = `-- name: ListGatewayKeysByUser :many
SELECT id, user_id, name, prefix, expires_at, revoked_at, last_used_at, created_at
FROM gateway_keys WHERE user_id = $1 ORDER BY created_at DESC, id
`

type ListGatewayKeysByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGatewayKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListGatewayKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeysByUserRow{}
	for rows.Next() {
		var i ListGatewayKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDisplayNames = `-- name: ListUserDisplayNames :many
SELECT id, display_name FROM users WHERE id = ANY($1::uuid[]) ORDER BY id
`

type ListUserDisplayNamesRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListUserDisplayNames(ctx context.Context, userIds []uuid.UUID) ([]ListUserDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, listUserDisplayNames, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDisplayNamesRow{}
	for rows.Next() {
		var i ListUserDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at FROM users
WHERE status <> 'deleted'
  AND ($1::user_status IS NULL OR status = $1)
  AND ($2::text = '' OR concat_ws(' ', email, display_name) ILIKE '%' || $2::text || '%')
ORDER BY created_at DESC, id
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Status     *UserStatus `json:"status"`
	Search     string      `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.DisabledAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBootstrapped = `-- name: MarkBootstrapped :execrows
UPDATE system_state SET bootstrapped_at = now() WHERE singleton = true AND bootstrapped_at IS NULL
`

func (q *Queries) MarkBootstrapped(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markBootstrapped)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markGatewayKeyRevoked = `-- name: MarkGatewayKeyRevoked :execrows
UPDATE gateway_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) MarkGatewayKeyRevoked(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markGatewayKeyRevoked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUserDeleted = `-- name: MarkUserDeleted :one
UPDATE users
SET status = 'deleted', disabled_at = NULL, deleted_at = now(),
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE id = $1 AND role = 'member' AND status <> 'deleted'
RETURNING id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at
`

func (q *Queries) MarkUserDeleted(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeGatewayKeysForUser = `-- name: RevokeGatewayKeysForUser :execrows
UPDATE gateway_keys SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeGatewayKeysForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGatewayKeysForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessionsExcept = `-- name: RevokeUserSessionsExcept :execrows
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeUserSessionsExceptParams struct {
	UserID             uuid.UUID `json:"user_id"`
	PreservedSessionID uuid.UUID `json:"preserved_session_id"`
}

func (q *Queries) RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessionsExcept, arg.UserID, arg.PreservedSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchGatewayKey = `-- name: TouchGatewayKey :exec
UPDATE gateway_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchGatewayKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchGatewayKey, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateOwnPassword = `-- name: UpdateOwnPassword :execrows
UPDATE users SET password_hash = $1, updated_at = now()
WHERE id = $2 AND password_hash = $3 AND status = 'active'
`

type UpdateOwnPasswordParams struct {
	ReplacementPasswordHash string    `json:"replacement_password_hash"`
	ID                      uuid.UUID `json:"id"`
	ExpectedPasswordHash    string    `json:"expected_password_hash"`
}

func (q *Queries) UpdateOwnPassword(ctx context.Context, arg UpdateOwnPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOwnPassword, arg.ReplacementPasswordHash, arg.ID, arg.ExpectedPasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET password_hash = $1, updated_at = now()
WHERE id = $2 AND status <> 'deleted'
RETURNING id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = lower($1), display_name = $2,
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE id = $3 AND role = 'member' AND status <> 'deleted' AND updated_at = $4
RETURNING id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Email,
		arg.DisplayName,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $1,
    disabled_at = CASE WHEN $1::user_status = 'disabled' THEN now() ELSE NULL END,
    deleted_at = NULL,
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE id = $2 AND role = 'member' AND status <> 'deleted'
RETURNING id, email, display_name, password_hash, role, status, disabled_at, deleted_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	Status UserStatus `json:"status"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
