// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeUserModel = `-- name: AuthorizeUserModel :exec
INSERT INTO model_authorizations (user_id, model_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AuthorizeUserModelParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ModelID uuid.UUID `json:"model_id"`
}

func (q *Queries) AuthorizeUserModel(ctx context.Context, arg AuthorizeUserModelParams) error {
	_, err := q.db.Exec(ctx, authorizeUserModel, arg.UserID, arg.ModelID)
	return err
}

const claimInvitation = `-- name: ClaimInvitation :execrows
UPDATE invitations
SET claimed_by = $1, claimed_at = now()
WHERE id = $2 AND claimed_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type ClaimInvitationParams struct {
	ClaimedBy *uuid.UUID `json:"claimed_by"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimInvitation, arg.ClaimedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE ($1::user_status IS NULL OR status = $1)
`

func (q *Queries) CountUsers(ctx context.Context, status *UserStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGatewayKey = `-- name: CreateGatewayKey :one
INSERT INTO gateway_keys (user_id, name, prefix, secret_digest, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, secret_digest, expires_at, revoked_at, last_used_at, created_at
`

type CreateGatewayKeyParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGatewayKey(ctx context.Context, arg CreateGatewayKeyParams) (GatewayKey, error) {
	row := q.db.QueryRow(ctx, createGatewayKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.SecretDigest,
		arg.ExpiresAt,
	)
	var i GatewayKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (code_digest, created_by, role, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code_digest, created_by, role, expires_at, claimed_by, claimed_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	CodeDigest []byte             `json:"code_digest"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	Role       UserRole           `json:"role"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.CodeDigest,
		arg.CreatedBy,
		arg.Role,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CreatedBy,
		&i.Role,
		&i.ExpiresAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_digest, csrf_digest, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_digest, csrf_digest, expires_at, revoked_at, last_seen_at, created_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, role, status, approved_at)
VALUES (lower($1), $2, $3, $4, $5, $6)
RETURNING id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Status       UserStatus         `json:"status"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.ApprovedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '1 day' OR revoked_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGatewayKeyByDigest = `-- name: GetGatewayKeyByDigest :one
SELECT k.id, k.user_id, k.name, k.prefix, k.secret_digest, k.expires_at, k.revoked_at, k.last_used_at, k.created_at, u.status AS user_status, u.role AS user_role
FROM gateway_keys k
JOIN users u ON u.id = k.user_id
WHERE k.secret_digest = $1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetGatewayKeyByDigestRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserStatus   UserStatus         `json:"user_status"`
	UserRole     UserRole           `json:"user_role"`
}

func (q *Queries) GetGatewayKeyByDigest(ctx context.Context, secretDigest []byte) (GetGatewayKeyByDigestRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyByDigest, secretDigest)
	var i GetGatewayKeyByDigestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UserStatus,
		&i.UserRole,
	)
	return i, err
}

const getInvitationByDigestForUpdate = `-- name: GetInvitationByDigestForUpdate :one
SELECT id, code_digest, created_by, role, expires_at, claimed_by, claimed_at, revoked_at, created_at FROM invitations WHERE code_digest = $1 FOR UPDATE
`

func (q *Queries) GetInvitationByDigestForUpdate(ctx context.Context, codeDigest []byte) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByDigestForUpdate, codeDigest)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CreatedBy,
		&i.Role,
		&i.ExpiresAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByDigest = `-- name: GetSessionByDigest :one
SELECT s.id, s.user_id, s.token_digest, s.csrf_digest, s.expires_at, s.revoked_at, s.last_seen_at, s.created_at, u.email, u.display_name, u.role, u.status AS user_status
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_digest = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
`

type GetSessionByDigestRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        UserRole           `json:"role"`
	UserStatus  UserStatus         `json:"user_status"`
}

func (q *Queries) GetSessionByDigest(ctx context.Context, tokenDigest []byte) (GetSessionByDigestRow, error) {
	row := q.db.QueryRow(ctx, getSessionByDigest, tokenDigest)
	var i GetSessionByDigestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.UserStatus,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isBootstrapped = `-- name: IsBootstrapped :one
SELECT CAST(bootstrapped_at IS NOT NULL AS boolean) AS bootstrapped FROM system_state WHERE singleton = true
`

func (q *Queries) IsBootstrapped(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isBootstrapped)
	var bootstrapped bool
	err := row.Scan(&bootstrapped)
	return bootstrapped, err
}

const isUserAuthorizedForModel = `-- name: IsUserAuthorizedForModel :one
SELECT EXISTS (SELECT 1 FROM model_authorizations WHERE user_id = $1 AND model_id = $2)
`

type IsUserAuthorizedForModelParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ModelID uuid.UUID `json:"model_id"`
}

func (q *Queries) IsUserAuthorizedForModel(ctx context.Context, arg IsUserAuthorizedForModelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAuthorizedForModel, arg.UserID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGatewayKeysByUser = `-- name: ListGatewayKeysByUser :many
SELECT id, user_id, name, prefix, expires_at, revoked_at, last_used_at, created_at
FROM gateway_keys WHERE user_id = $1 ORDER BY created_at DESC, id
`

type ListGatewayKeysByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGatewayKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListGatewayKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeysByUserRow{}
	for rows.Next() {
		var i ListGatewayKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, code_digest, created_by, role, expires_at, claimed_by, claimed_at, revoked_at, created_at FROM invitations ORDER BY created_at DESC, id LIMIT $2 OFFSET $1
`

type ListInvitationsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.CodeDigest,
			&i.CreatedBy,
			&i.Role,
			&i.ExpiresAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users
WHERE ($1::user_status IS NULL OR status = $1)
ORDER BY created_at DESC, id
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Status     *UserStatus `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.ApprovedAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBootstrapped = `-- name: MarkBootstrapped :execrows
UPDATE system_state SET bootstrapped_at = now() WHERE singleton = true AND bootstrapped_at IS NULL
`

func (q *Queries) MarkBootstrapped(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markBootstrapped)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeGatewayKey = `-- name: RevokeGatewayKey :execrows
UPDATE gateway_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeGatewayKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGatewayKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL AND claimed_at IS NULL
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOwnedGatewayKey = `-- name: RevokeOwnedGatewayKey :execrows
UPDATE gateway_keys SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeOwnedGatewayKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeOwnedGatewayKey(ctx context.Context, arg RevokeOwnedGatewayKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOwnedGatewayKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserModel = `-- name: RevokeUserModel :execrows
DELETE FROM model_authorizations WHERE user_id = $1 AND model_id = $2
`

type RevokeUserModelParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ModelID uuid.UUID `json:"model_id"`
}

func (q *Queries) RevokeUserModel(ctx context.Context, arg RevokeUserModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserModel, arg.UserID, arg.ModelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const touchGatewayKey = `-- name: TouchGatewayKey :exec
UPDATE gateway_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchGatewayKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchGatewayKey, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $1,
    approved_at = CASE WHEN $1::user_status = 'active' THEN coalesce(approved_at, now()) ELSE approved_at END,
    disabled_at = CASE WHEN $1::user_status = 'disabled' THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	Status UserStatus `json:"status"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
