// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindGatewayKeyModel = `-- name: BindGatewayKeyModel :exec
INSERT INTO gateway_key_models (gateway_key_id, model_id)
VALUES ($1, $2)
`

type BindGatewayKeyModelParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	ModelID      uuid.UUID `json:"model_id"`
}

func (q *Queries) BindGatewayKeyModel(ctx context.Context, arg BindGatewayKeyModelParams) error {
	_, err := q.db.Exec(ctx, bindGatewayKeyModel, arg.GatewayKeyID, arg.ModelID)
	return err
}

const claimGatewayKeyMutation = `-- name: ClaimGatewayKeyMutation :one
INSERT INTO gateway_key_mutations (actor_user_id, idempotency_key, request_fingerprint, request_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (actor_user_id, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, idempotency_key, request_fingerprint, request_id, gateway_key_id, result, created_at
`

type ClaimGatewayKeyMutationParams struct {
	ActorUserID        uuid.UUID `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID `json:"idempotency_key"`
	RequestFingerprint []byte    `json:"request_fingerprint"`
	RequestID          string    `json:"request_id"`
}

func (q *Queries) ClaimGatewayKeyMutation(ctx context.Context, arg ClaimGatewayKeyMutationParams) (GatewayKeyMutation, error) {
	row := q.db.QueryRow(ctx, claimGatewayKeyMutation,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.RequestID,
	)
	var i GatewayKeyMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.GatewayKeyID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const claimInvitation = `-- name: ClaimInvitation :execrows
UPDATE invitations
SET claimed_by = $1, claimed_at = now()
WHERE id = $2 AND claimed_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type ClaimInvitationParams struct {
	ClaimedBy *uuid.UUID `json:"claimed_by"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimInvitation, arg.ClaimedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimInvitationMutation = `-- name: ClaimInvitationMutation :one
INSERT INTO invitation_mutations (actor_user_id, idempotency_key, request_fingerprint, request_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (actor_user_id, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, idempotency_key, request_fingerprint, request_id, invitation_id, result, created_at
`

type ClaimInvitationMutationParams struct {
	ActorUserID        uuid.UUID `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID `json:"idempotency_key"`
	RequestFingerprint []byte    `json:"request_fingerprint"`
	RequestID          string    `json:"request_id"`
}

func (q *Queries) ClaimInvitationMutation(ctx context.Context, arg ClaimInvitationMutationParams) (InvitationMutation, error) {
	row := q.db.QueryRow(ctx, claimInvitationMutation,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.RequestID,
	)
	var i InvitationMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.InvitationID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const claimMemberPasswordResetMutation = `-- name: ClaimMemberPasswordResetMutation :one
INSERT INTO member_password_reset_mutations (
  actor_user_id, idempotency_key, user_id, request_fingerprint, request_id
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (actor_user_id, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, idempotency_key, user_id, request_fingerprint, request_id, result, created_at
`

type ClaimMemberPasswordResetMutationParams struct {
	ActorUserID        uuid.UUID `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID `json:"idempotency_key"`
	UserID             uuid.UUID `json:"user_id"`
	RequestFingerprint []byte    `json:"request_fingerprint"`
	RequestID          string    `json:"request_id"`
}

func (q *Queries) ClaimMemberPasswordResetMutation(ctx context.Context, arg ClaimMemberPasswordResetMutationParams) (MemberPasswordResetMutation, error) {
	row := q.db.QueryRow(ctx, claimMemberPasswordResetMutation,
		arg.ActorUserID,
		arg.IdempotencyKey,
		arg.UserID,
		arg.RequestFingerprint,
		arg.RequestID,
	)
	var i MemberPasswordResetMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeGatewayKeyMutation = `-- name: CompleteGatewayKeyMutation :one
UPDATE gateway_key_mutations
SET gateway_key_id = $1, result = $2
WHERE id = $3
RETURNING id, actor_user_id, idempotency_key, request_fingerprint, request_id, gateway_key_id, result, created_at
`

type CompleteGatewayKeyMutationParams struct {
	GatewayKeyID *uuid.UUID `json:"gateway_key_id"`
	Result       []byte     `json:"result"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) CompleteGatewayKeyMutation(ctx context.Context, arg CompleteGatewayKeyMutationParams) (GatewayKeyMutation, error) {
	row := q.db.QueryRow(ctx, completeGatewayKeyMutation, arg.GatewayKeyID, arg.Result, arg.ID)
	var i GatewayKeyMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.GatewayKeyID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeInvitationMutation = `-- name: CompleteInvitationMutation :one
UPDATE invitation_mutations
SET invitation_id = $1, result = $2
WHERE id = $3 AND invitation_id IS NULL
RETURNING id, actor_user_id, idempotency_key, request_fingerprint, request_id, invitation_id, result, created_at
`

type CompleteInvitationMutationParams struct {
	InvitationID *uuid.UUID `json:"invitation_id"`
	Result       []byte     `json:"result"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) CompleteInvitationMutation(ctx context.Context, arg CompleteInvitationMutationParams) (InvitationMutation, error) {
	row := q.db.QueryRow(ctx, completeInvitationMutation, arg.InvitationID, arg.Result, arg.ID)
	var i InvitationMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.InvitationID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeMemberPasswordResetMutation = `-- name: CompleteMemberPasswordResetMutation :one
UPDATE member_password_reset_mutations
SET result = $1
WHERE id = $2
RETURNING id, actor_user_id, idempotency_key, user_id, request_fingerprint, request_id, result, created_at
`

type CompleteMemberPasswordResetMutationParams struct {
	Result []byte    `json:"result"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) CompleteMemberPasswordResetMutation(ctx context.Context, arg CompleteMemberPasswordResetMutationParams) (MemberPasswordResetMutation, error) {
	row := q.db.QueryRow(ctx, completeMemberPasswordResetMutation, arg.Result, arg.ID)
	var i MemberPasswordResetMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE ($1::user_status IS NULL OR status = $1)
`

func (q *Queries) CountUsers(ctx context.Context, status *UserStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGatewayKey = `-- name: CreateGatewayKey :one
INSERT INTO gateway_keys (user_id, name, prefix, secret_digest, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, secret_digest, expires_at, revoked_at, last_used_at, created_at
`

type CreateGatewayKeyParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGatewayKey(ctx context.Context, arg CreateGatewayKeyParams) (GatewayKey, error) {
	row := q.db.QueryRow(ctx, createGatewayKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.SecretDigest,
		arg.ExpiresAt,
	)
	var i GatewayKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (code_digest, code_prefix, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code_digest, code_prefix, created_by, expires_at, claimed_by, claimed_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	CodeDigest []byte             `json:"code_digest"`
	CodePrefix string             `json:"code_prefix"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.CodeDigest,
		arg.CodePrefix,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CodePrefix,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_digest, csrf_digest, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_digest, csrf_digest, expires_at, revoked_at, last_seen_at, created_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, role, status, approved_at)
VALUES (lower($1), $2, $3, $4, $5, $6)
RETURNING id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Status       UserStatus         `json:"status"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.ApprovedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '1 day' OR revoked_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGatewayKeyByDigest = `-- name: GetGatewayKeyByDigest :one
SELECT k.id, k.user_id, k.name, k.prefix, k.secret_digest, k.expires_at, k.revoked_at, k.last_used_at, k.created_at, u.status AS user_status, u.role AS user_role
FROM gateway_keys k
JOIN users u ON u.id = k.user_id
WHERE k.secret_digest = $1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetGatewayKeyByDigestRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserStatus   UserStatus         `json:"user_status"`
	UserRole     UserRole           `json:"user_role"`
}

func (q *Queries) GetGatewayKeyByDigest(ctx context.Context, secretDigest []byte) (GetGatewayKeyByDigestRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyByDigest, secretDigest)
	var i GetGatewayKeyByDigestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UserStatus,
		&i.UserRole,
	)
	return i, err
}

const getGatewayKeyForReplacement = `-- name: GetGatewayKeyForReplacement :one
SELECT id, user_id, name, prefix, expires_at, revoked_at, last_used_at, created_at
FROM gateway_keys
WHERE id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
FOR UPDATE
`

type GetGatewayKeyForReplacementRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGatewayKeyForReplacement(ctx context.Context, id uuid.UUID) (GetGatewayKeyForReplacementRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyForReplacement, id)
	var i GetGatewayKeyForReplacementRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGatewayKeyForRevocation = `-- name: GetGatewayKeyForRevocation :one
SELECT id, user_id, revoked_at
FROM gateway_keys
WHERE id = $1
FOR UPDATE
`

type GetGatewayKeyForRevocationRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetGatewayKeyForRevocation(ctx context.Context, id uuid.UUID) (GetGatewayKeyForRevocationRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyForRevocation, id)
	var i GetGatewayKeyForRevocationRow
	err := row.Scan(&i.ID, &i.UserID, &i.RevokedAt)
	return i, err
}

const getGatewayKeyMutation = `-- name: GetGatewayKeyMutation :one
SELECT id, actor_user_id, idempotency_key, request_fingerprint, request_id, gateway_key_id, result, created_at FROM gateway_key_mutations
WHERE actor_user_id = $1 AND idempotency_key = $2
`

type GetGatewayKeyMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetGatewayKeyMutation(ctx context.Context, arg GetGatewayKeyMutationParams) (GatewayKeyMutation, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyMutation, arg.ActorUserID, arg.IdempotencyKey)
	var i GatewayKeyMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.GatewayKeyID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getGatewayKeyPrincipalByID = `-- name: GetGatewayKeyPrincipalByID :one
SELECT k.id, k.user_id, k.name, k.prefix, k.secret_digest, k.expires_at, k.revoked_at, k.last_used_at, k.created_at, u.status AS user_status, u.role AS user_role
FROM gateway_keys k
JOIN users u ON u.id = k.user_id
WHERE k.id = $1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetGatewayKeyPrincipalByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserStatus   UserStatus         `json:"user_status"`
	UserRole     UserRole           `json:"user_role"`
}

func (q *Queries) GetGatewayKeyPrincipalByID(ctx context.Context, id uuid.UUID) (GetGatewayKeyPrincipalByIDRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyPrincipalByID, id)
	var i GetGatewayKeyPrincipalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UserStatus,
		&i.UserRole,
	)
	return i, err
}

const getGatewayKeyRevocationState = `-- name: GetGatewayKeyRevocationState :one
SELECT user_id, revoked_at
FROM gateway_keys
WHERE id = $1
`

type GetGatewayKeyRevocationStateRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetGatewayKeyRevocationState(ctx context.Context, id uuid.UUID) (GetGatewayKeyRevocationStateRow, error) {
	row := q.db.QueryRow(ctx, getGatewayKeyRevocationState, id)
	var i GetGatewayKeyRevocationStateRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const getInvitationByDigestForUpdate = `-- name: GetInvitationByDigestForUpdate :one
SELECT id, code_digest, code_prefix, created_by, expires_at, claimed_by, claimed_at, revoked_at, created_at FROM invitations WHERE code_digest = $1 FOR UPDATE
`

func (q *Queries) GetInvitationByDigestForUpdate(ctx context.Context, codeDigest []byte) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByDigestForUpdate, codeDigest)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CodePrefix,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationMutation = `-- name: GetInvitationMutation :one
SELECT id, actor_user_id, idempotency_key, request_fingerprint, request_id, invitation_id, result, created_at FROM invitation_mutations
WHERE actor_user_id = $1 AND idempotency_key = $2
`

type GetInvitationMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetInvitationMutation(ctx context.Context, arg GetInvitationMutationParams) (InvitationMutation, error) {
	row := q.db.QueryRow(ctx, getInvitationMutation, arg.ActorUserID, arg.IdempotencyKey)
	var i InvitationMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.InvitationID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberPasswordResetMutation = `-- name: GetMemberPasswordResetMutation :one
SELECT id, actor_user_id, idempotency_key, user_id, request_fingerprint, request_id, result, created_at FROM member_password_reset_mutations
WHERE actor_user_id = $1 AND idempotency_key = $2
`

type GetMemberPasswordResetMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetMemberPasswordResetMutation(ctx context.Context, arg GetMemberPasswordResetMutationParams) (MemberPasswordResetMutation, error) {
	row := q.db.QueryRow(ctx, getMemberPasswordResetMutation, arg.ActorUserID, arg.IdempotencyKey)
	var i MemberPasswordResetMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getModelForGatewayKeyBinding = `-- name: GetModelForGatewayKeyBinding :one
SELECT model.model_id AS id, model.public_name
FROM active_config active
JOIN config_revision_models model ON model.revision_id = active.revision_id
WHERE active.singleton = true AND model.model_id = $1
  AND EXISTS (
    SELECT 1
    FROM config_revision_routes route
    WHERE route.revision_id = active.revision_id
      AND route.model_id = model.model_id
  )
FOR SHARE OF active
`

type GetModelForGatewayKeyBindingRow struct {
	ID         uuid.UUID `json:"id"`
	PublicName string    `json:"public_name"`
}

func (q *Queries) GetModelForGatewayKeyBinding(ctx context.Context, id uuid.UUID) (GetModelForGatewayKeyBindingRow, error) {
	row := q.db.QueryRow(ctx, getModelForGatewayKeyBinding, id)
	var i GetModelForGatewayKeyBindingRow
	err := row.Scan(&i.ID, &i.PublicName)
	return i, err
}

const getSessionByDigest = `-- name: GetSessionByDigest :one
SELECT s.id, s.user_id, s.token_digest, s.csrf_digest, s.expires_at, s.revoked_at, s.last_seen_at, s.created_at, u.email, u.display_name, u.role, u.status AS user_status
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_digest = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
`

type GetSessionByDigestRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        UserRole           `json:"role"`
	UserStatus  UserStatus         `json:"user_status"`
}

func (q *Queries) GetSessionByDigest(ctx context.Context, tokenDigest []byte) (GetSessionByDigestRow, error) {
	row := q.db.QueryRow(ctx, getSessionByDigest, tokenDigest)
	var i GetSessionByDigestRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.UserStatus,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAdministrativeRecovery = `-- name: GetUserForAdministrativeRecovery :one
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForAdministrativeRecovery(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForAdministrativeRecovery, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForGatewayKeyCreation = `-- name: GetUserForGatewayKeyCreation :one
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users WHERE id = $1 FOR SHARE
`

func (q *Queries) GetUserForGatewayKeyCreation(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForGatewayKeyCreation, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isBootstrapped = `-- name: IsBootstrapped :one
SELECT CAST(bootstrapped_at IS NOT NULL AS boolean) AS bootstrapped FROM system_state WHERE singleton = true
`

func (q *Queries) IsBootstrapped(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isBootstrapped)
	var bootstrapped bool
	err := row.Scan(&bootstrapped)
	return bootstrapped, err
}

const isGatewayKeyAuthorizedForModel = `-- name: IsGatewayKeyAuthorizedForModel :one
SELECT EXISTS (
  SELECT 1 FROM gateway_key_models
  WHERE gateway_key_id = $1 AND model_id = $2
)
`

type IsGatewayKeyAuthorizedForModelParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	ModelID      uuid.UUID `json:"model_id"`
}

func (q *Queries) IsGatewayKeyAuthorizedForModel(ctx context.Context, arg IsGatewayKeyAuthorizedForModelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGatewayKeyAuthorizedForModel, arg.GatewayKeyID, arg.ModelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGatewayKeyModelBindingsByKey = `-- name: ListGatewayKeyModelBindingsByKey :many
SELECT gkm.model_id, published.public_name
FROM gateway_key_models gkm
JOIN LATERAL (
  SELECT model.public_name
  FROM config_revision_models model
  JOIN config_revisions revision ON revision.id = model.revision_id
  WHERE model.model_id = gkm.model_id AND revision.published_at IS NOT NULL
  ORDER BY revision.revision DESC
  LIMIT 1
) published ON true
WHERE gkm.gateway_key_id = $1
ORDER BY published.public_name, gkm.model_id
`

type ListGatewayKeyModelBindingsByKeyRow struct {
	ModelID    uuid.UUID `json:"model_id"`
	PublicName string    `json:"public_name"`
}

func (q *Queries) ListGatewayKeyModelBindingsByKey(ctx context.Context, gatewayKeyID uuid.UUID) ([]ListGatewayKeyModelBindingsByKeyRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeyModelBindingsByKey, gatewayKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeyModelBindingsByKeyRow{}
	for rows.Next() {
		var i ListGatewayKeyModelBindingsByKeyRow
		if err := rows.Scan(&i.ModelID, &i.PublicName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayKeyModelBindingsByUser = `-- name: ListGatewayKeyModelBindingsByUser :many
SELECT gkm.gateway_key_id, gkm.model_id, published.public_name
FROM gateway_key_models gkm
JOIN gateway_keys k ON k.id = gkm.gateway_key_id
JOIN LATERAL (
  SELECT model.public_name
  FROM config_revision_models model
  JOIN config_revisions revision ON revision.id = model.revision_id
  WHERE model.model_id = gkm.model_id AND revision.published_at IS NOT NULL
  ORDER BY revision.revision DESC
  LIMIT 1
) published ON true
WHERE k.user_id = $1
ORDER BY gkm.gateway_key_id, published.public_name, gkm.model_id
`

type ListGatewayKeyModelBindingsByUserRow struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	ModelID      uuid.UUID `json:"model_id"`
	PublicName   string    `json:"public_name"`
}

func (q *Queries) ListGatewayKeyModelBindingsByUser(ctx context.Context, userID uuid.UUID) ([]ListGatewayKeyModelBindingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeyModelBindingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeyModelBindingsByUserRow{}
	for rows.Next() {
		var i ListGatewayKeyModelBindingsByUserRow
		if err := rows.Scan(&i.GatewayKeyID, &i.ModelID, &i.PublicName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayKeysByUser = `-- name: ListGatewayKeysByUser :many
SELECT id, user_id, name, prefix, expires_at, revoked_at, last_used_at, created_at
FROM gateway_keys WHERE user_id = $1 ORDER BY created_at DESC, id
`

type ListGatewayKeysByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGatewayKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListGatewayKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listGatewayKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayKeysByUserRow{}
	for rows.Next() {
		var i ListGatewayKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, code_digest, code_prefix, created_by, expires_at, claimed_by, claimed_at, revoked_at, created_at FROM invitations ORDER BY created_at DESC, id LIMIT $2 OFFSET $1
`

type ListInvitationsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.CodeDigest,
			&i.CodePrefix,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDisplayNames = `-- name: ListUserDisplayNames :many
SELECT id, display_name
FROM users
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type ListUserDisplayNamesRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListUserDisplayNames(ctx context.Context, userIds []uuid.UUID) ([]ListUserDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, listUserDisplayNames, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDisplayNamesRow{}
	for rows.Next() {
		var i ListUserDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at FROM users
WHERE ($1::user_status IS NULL OR status = $1)
ORDER BY created_at DESC, id
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Status     *UserStatus `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.ApprovedAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBootstrapped = `-- name: MarkBootstrapped :execrows
UPDATE system_state SET bootstrapped_at = now() WHERE singleton = true AND bootstrapped_at IS NULL
`

func (q *Queries) MarkBootstrapped(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markBootstrapped)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markGatewayKeyRevoked = `-- name: MarkGatewayKeyRevoked :execrows
UPDATE gateway_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) MarkGatewayKeyRevoked(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markGatewayKeyRevoked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL AND claimed_at IS NULL
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessionsExcept = `-- name: RevokeUserSessionsExcept :execrows
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeUserSessionsExceptParams struct {
	UserID             uuid.UUID `json:"user_id"`
	PreservedSessionID uuid.UUID `json:"preserved_session_id"`
}

func (q *Queries) RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessionsExcept, arg.UserID, arg.PreservedSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchGatewayKey = `-- name: TouchGatewayKey :exec
UPDATE gateway_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchGatewayKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchGatewayKey, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateOwnPassword = `-- name: UpdateOwnPassword :execrows
UPDATE users SET password_hash = $1, updated_at = now()
WHERE id = $2 AND password_hash = $3
`

type UpdateOwnPasswordParams struct {
	ReplacementPasswordHash string    `json:"replacement_password_hash"`
	ID                      uuid.UUID `json:"id"`
	ExpectedPasswordHash    string    `json:"expected_password_hash"`
}

func (q *Queries) UpdateOwnPassword(ctx context.Context, arg UpdateOwnPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOwnPassword, arg.ReplacementPasswordHash, arg.ID, arg.ExpectedPasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET password_hash = $1, updated_at = now()
WHERE id = $2
RETURNING id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $1,
    approved_at = CASE WHEN $1::user_status = 'active' THEN coalesce(approved_at, now()) ELSE approved_at END,
    disabled_at = CASE WHEN $1::user_status = 'disabled' THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, email, display_name, password_hash, role, status, approved_at, disabled_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	Status UserStatus `json:"status"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ApprovedAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
