// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeLedgerReservation = `-- name: CompleteLedgerReservation :one
UPDATE ledger_reservations
SET state = $1, charged_tokens = $2, usage_source = $3, terminal_event_id = $4, updated_at = now()
WHERE id = $5 AND state = 'reserved'
RETURNING id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at
`

type CompleteLedgerReservationParams struct {
	State           ReservationState `json:"state"`
	ChargedTokens   int64            `json:"charged_tokens"`
	UsageSource     UsageSource      `json:"usage_source"`
	TerminalEventID *uuid.UUID       `json:"terminal_event_id"`
	ID              uuid.UUID        `json:"id"`
}

func (q *Queries) CompleteLedgerReservation(ctx context.Context, arg CompleteLedgerReservationParams) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, completeLedgerReservation,
		arg.State,
		arg.ChargedTokens,
		arg.UsageSource,
		arg.TerminalEventID,
		arg.ID,
	)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRequest = `-- name: CompleteRequest :one
UPDATE requests SET status = 'completed', input_tokens = $1, output_tokens = $2, usage_source = $3, error_kind = NULL, error_detail = NULL, completed_at = now(), updated_at = now()
WHERE id = $4 RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type CompleteRequestParams struct {
	InputTokens  *int64      `json:"input_tokens"`
	OutputTokens *int64      `json:"output_tokens"`
	UsageSource  UsageSource `json:"usage_source"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) CompleteRequest(ctx context.Context, arg CompleteRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, completeRequest,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO request_attempts (request_id, credential_id, sequence, status)
VALUES ($1, $2, $3, $4) RETURNING id, request_id, credential_id, sequence, status, upstream_request_id, http_status, error_kind, retry_after_at, sent_at, first_byte_at, completed_at, created_at
`

type CreateAttemptParams struct {
	RequestID    uuid.UUID     `json:"request_id"`
	CredentialID uuid.UUID     `json:"credential_id"`
	Sequence     int32         `json:"sequence"`
	Status       AttemptStatus `json:"status"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (RequestAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.RequestID,
		arg.CredentialID,
		arg.Sequence,
		arg.Status,
	)
	var i RequestAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CredentialID,
		&i.Sequence,
		&i.Status,
		&i.UpstreamRequestID,
		&i.HttpStatus,
		&i.ErrorKind,
		&i.RetryAfterAt,
		&i.SentAt,
		&i.FirstByteAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEntitlement = `-- name: CreateEntitlement :one
INSERT INTO entitlements (user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at
`

type CreateEntitlementParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
}

func (q *Queries) CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, createEntitlement,
		arg.UserID,
		arg.Plan,
		arg.ResourceDomain,
		arg.ModelID,
		arg.GrantedTokens,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.ConcurrencyLimit,
		arg.RpmLimit,
		arg.TpmLimit,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.ResourceDomain,
		&i.ModelID,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEvent = `-- name: CreateLedgerEvent :one
INSERT INTO ledger_events (user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by, created_at
`

type CreateLedgerEventParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	EntitlementID  uuid.UUID       `json:"entitlement_id"`
	RequestID      *uuid.UUID      `json:"request_id"`
	ReservationID  *uuid.UUID      `json:"reservation_id"`
	Kind           LedgerEventKind `json:"kind"`
	TokenDelta     int64           `json:"token_delta"`
	ReservedTokens int64           `json:"reserved_tokens"`
	InputTokens    int64           `json:"input_tokens"`
	OutputTokens   int64           `json:"output_tokens"`
	UsageSource    UsageSource     `json:"usage_source"`
	SourceEventID  *uuid.UUID      `json:"source_event_id"`
	Note           *string         `json:"note"`
	CreatedBy      *uuid.UUID      `json:"created_by"`
}

func (q *Queries) CreateLedgerEvent(ctx context.Context, arg CreateLedgerEventParams) (LedgerEvent, error) {
	row := q.db.QueryRow(ctx, createLedgerEvent,
		arg.UserID,
		arg.EntitlementID,
		arg.RequestID,
		arg.ReservationID,
		arg.Kind,
		arg.TokenDelta,
		arg.ReservedTokens,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.SourceEventID,
		arg.Note,
		arg.CreatedBy,
	)
	var i LedgerEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntitlementID,
		&i.RequestID,
		&i.ReservationID,
		&i.Kind,
		&i.TokenDelta,
		&i.ReservedTokens,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.SourceEventID,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerReservation = `-- name: CreateLedgerReservation :one
INSERT INTO ledger_reservations (id, entitlement_id, request_id, state, reserved_tokens, reserve_event_id)
VALUES ($1, $2, $3, 'reserved', $4, $5)
RETURNING id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at
`

type CreateLedgerReservationParams struct {
	ID             uuid.UUID `json:"id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
	RequestID      uuid.UUID `json:"request_id"`
	ReservedTokens int64     `json:"reserved_tokens"`
	ReserveEventID uuid.UUID `json:"reserve_event_id"`
}

func (q *Queries) CreateLedgerReservation(ctx context.Context, arg CreateLedgerReservationParams) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, createLedgerReservation,
		arg.ID,
		arg.EntitlementID,
		arg.RequestID,
		arg.ReservedTokens,
		arg.ReserveEventID,
	)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type CreateRequestParams struct {
	IdempotencyKey   *string        `json:"idempotency_key"`
	RequestDigest    []byte         `json:"request_digest"`
	UserID           uuid.UUID      `json:"user_id"`
	GatewayKeyID     uuid.UUID      `json:"gateway_key_id"`
	ModelID          uuid.UUID      `json:"model_id"`
	EntitlementID    uuid.UUID      `json:"entitlement_id"`
	ConfigRevisionID *uuid.UUID     `json:"config_revision_id"`
	ResourceDomain   ResourceDomain `json:"resource_domain"`
	Status           RequestStatus  `json:"status"`
	Stream           bool           `json:"stream"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.UserID,
		arg.GatewayKeyID,
		arg.ModelID,
		arg.EntitlementID,
		arg.ConfigRevisionID,
		arg.ResourceDomain,
		arg.Status,
		arg.Stream,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResponseRecord = `-- name: CreateResponseRecord :one
INSERT INTO response_records (request_id, status) VALUES ($1, $2) RETURNING id, request_id, status, output, error, cancel_requested_at, created_at, updated_at
`

type CreateResponseRecordParams struct {
	RequestID uuid.UUID     `json:"request_id"`
	Status    RequestStatus `json:"status"`
}

func (q *Queries) CreateResponseRecord(ctx context.Context, arg CreateResponseRecordParams) (ResponseRecord, error) {
	row := q.db.QueryRow(ctx, createResponseRecord, arg.RequestID, arg.Status)
	var i ResponseRecord
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Status,
		&i.Output,
		&i.Error,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const entitlementBalance = `-- name: EntitlementBalance :one
SELECT coalesce(sum(token_delta), 0)::bigint FROM ledger_events WHERE entitlement_id = $1
`

func (q *Queries) EntitlementBalance(ctx context.Context, entitlementID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, entitlementBalance, entitlementID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const failRequestWithUsage = `-- name: FailRequestWithUsage :one
UPDATE requests
SET status = 'failed', input_tokens = $1, output_tokens = $2, usage_source = $3,
    error_kind = $4, error_detail = $5, completed_at = now(), updated_at = now()
WHERE id = $6
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type FailRequestWithUsageParams struct {
	InputTokens  *int64      `json:"input_tokens"`
	OutputTokens *int64      `json:"output_tokens"`
	UsageSource  UsageSource `json:"usage_source"`
	ErrorKind    *string     `json:"error_kind"`
	ErrorDetail  *string     `json:"error_detail"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) FailRequestWithUsage(ctx context.Context, arg FailRequestWithUsageParams) (Request, error) {
	row := q.db.QueryRow(ctx, failRequestWithUsage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.ErrorKind,
		arg.ErrorDetail,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedModelDomain = `-- name: GetAuthorizedModelDomain :one
SELECT m.resource_domain
FROM models m
JOIN model_authorizations a ON a.model_id = m.id AND a.user_id = $1
WHERE m.id = $2 AND m.enabled = true
`

type GetAuthorizedModelDomainParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ModelID uuid.UUID `json:"model_id"`
}

func (q *Queries) GetAuthorizedModelDomain(ctx context.Context, arg GetAuthorizedModelDomainParams) (ResourceDomain, error) {
	row := q.db.QueryRow(ctx, getAuthorizedModelDomain, arg.UserID, arg.ModelID)
	var resource_domain ResourceDomain
	err := row.Scan(&resource_domain)
	return resource_domain, err
}

const getEntitlementByGrantIdempotency = `-- name: GetEntitlementByGrantIdempotency :one
SELECT e.id, e.user_id, e.plan, e.resource_domain, e.model_id, e.granted_tokens, e.starts_at, e.expires_at, e.concurrency_limit, e.rpm_limit, e.tpm_limit, e.created_at, le.note AS grant_note
FROM ledger_events le
JOIN entitlements e ON e.id = le.entitlement_id
WHERE le.source_event_id = $1
  AND le.kind = 'grant'
  AND le.created_by = $2
`

type GetEntitlementByGrantIdempotencyParams struct {
	SourceEventID *uuid.UUID `json:"source_event_id"`
	CreatedBy     *uuid.UUID `json:"created_by"`
}

type GetEntitlementByGrantIdempotencyRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	GrantNote        *string            `json:"grant_note"`
}

func (q *Queries) GetEntitlementByGrantIdempotency(ctx context.Context, arg GetEntitlementByGrantIdempotencyParams) (GetEntitlementByGrantIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getEntitlementByGrantIdempotency, arg.SourceEventID, arg.CreatedBy)
	var i GetEntitlementByGrantIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.ResourceDomain,
		&i.ModelID,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedAt,
		&i.GrantNote,
	)
	return i, err
}

const getEntitlementForUpdate = `-- name: GetEntitlementForUpdate :one
SELECT id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at FROM entitlements WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetEntitlementForUpdate(ctx context.Context, id uuid.UUID) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlementForUpdate, id)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.ResourceDomain,
		&i.ModelID,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerReservationByRequest = `-- name: GetLedgerReservationByRequest :one
SELECT id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at FROM ledger_reservations WHERE request_id = $1
`

func (q *Queries) GetLedgerReservationByRequest(ctx context.Context, requestID uuid.UUID) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, getLedgerReservationByRequest, requestID)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerReservationByRequestForUpdate = `-- name: GetLedgerReservationByRequestForUpdate :one
SELECT id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at FROM ledger_reservations WHERE request_id = $1 FOR UPDATE
`

func (q *Queries) GetLedgerReservationByRequestForUpdate(ctx context.Context, requestID uuid.UUID) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, getLedgerReservationByRequestForUpdate, requestID)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerReservationForUpdate = `-- name: GetLedgerReservationForUpdate :one
SELECT id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at FROM ledger_reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetLedgerReservationForUpdate(ctx context.Context, id uuid.UUID) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, getLedgerReservationForUpdate, id)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDomain = `-- name: GetModelDomain :one
SELECT resource_domain FROM models WHERE id = $1
`

func (q *Queries) GetModelDomain(ctx context.Context, modelID uuid.UUID) (ResourceDomain, error) {
	row := q.db.QueryRow(ctx, getModelDomain, modelID)
	var resource_domain ResourceDomain
	err := row.Scan(&resource_domain)
	return resource_domain, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestByIdempotencyKey = `-- name: GetRequestByIdempotencyKey :one
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests WHERE gateway_key_id = $1 AND idempotency_key = $2
`

type GetRequestByIdempotencyKeyParams struct {
	GatewayKeyID   uuid.UUID `json:"gateway_key_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetRequestByIdempotencyKey(ctx context.Context, arg GetRequestByIdempotencyKeyParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByIdempotencyKey, arg.GatewayKeyID, arg.IdempotencyKey)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestForUpdate = `-- name: GetRequestForUpdate :one
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRequestForUpdate(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestForUpdate, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResponseRecord = `-- name: GetResponseRecord :one
SELECT id, request_id, status, output, error, cancel_requested_at, created_at, updated_at FROM response_records WHERE id = $1
`

func (q *Queries) GetResponseRecord(ctx context.Context, id uuid.UUID) (ResponseRecord, error) {
	row := q.db.QueryRow(ctx, getResponseRecord, id)
	var i ResponseRecord
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Status,
		&i.Output,
		&i.Error,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isGatewayKeyOwnedByUser = `-- name: IsGatewayKeyOwnedByUser :one
SELECT EXISTS (
  SELECT 1 FROM gateway_keys
  WHERE id = $1
    AND user_id = $2
    AND revoked_at IS NULL
    AND (expires_at IS NULL OR expires_at > now())
)
`

type IsGatewayKeyOwnedByUserParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) IsGatewayKeyOwnedByUser(ctx context.Context, arg IsGatewayKeyOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGatewayKeyOwnedByUser, arg.GatewayKeyID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveEntitlements = `-- name: ListActiveEntitlements :many
SELECT id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at FROM entitlements WHERE user_id = $1 AND starts_at <= now() AND expires_at > now() ORDER BY resource_domain, expires_at, id
`

func (q *Queries) ListActiveEntitlements(ctx context.Context, userID uuid.UUID) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listActiveEntitlements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.ResourceDomain,
			&i.ModelID,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicableEntitlementsForUpdate = `-- name: ListApplicableEntitlementsForUpdate :many
SELECT id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at FROM entitlements
WHERE user_id = $1
  AND resource_domain = $2
  AND starts_at <= now() AND expires_at > now()
  AND (model_id IS NULL OR model_id = $3)
ORDER BY (model_id IS NOT NULL) DESC, expires_at, id
FOR UPDATE
`

type ListApplicableEntitlementsForUpdateParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	ResourceDomain ResourceDomain `json:"resource_domain"`
	ModelID        *uuid.UUID     `json:"model_id"`
}

func (q *Queries) ListApplicableEntitlementsForUpdate(ctx context.Context, arg ListApplicableEntitlementsForUpdateParams) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listApplicableEntitlementsForUpdate, arg.UserID, arg.ResourceDomain, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.ResourceDomain,
			&i.ModelID,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitlementsWithBalance = `-- name: ListEntitlementsWithBalance :many
SELECT e.id, e.user_id, e.plan, e.resource_domain, e.model_id, e.granted_tokens, e.starts_at, e.expires_at, e.concurrency_limit, e.rpm_limit, e.tpm_limit, e.created_at, coalesce(sum(le.token_delta), 0)::bigint AS balance_tokens
FROM entitlements e
LEFT JOIN ledger_events le ON le.entitlement_id = e.id
WHERE ($1::uuid IS NULL OR e.user_id = $1)
GROUP BY e.id
ORDER BY e.created_at DESC, e.id
LIMIT $3 OFFSET $2
`

type ListEntitlementsWithBalanceParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListEntitlementsWithBalanceRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BalanceTokens    int64              `json:"balance_tokens"`
}

func (q *Queries) ListEntitlementsWithBalance(ctx context.Context, arg ListEntitlementsWithBalanceParams) ([]ListEntitlementsWithBalanceRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementsWithBalance, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitlementsWithBalanceRow{}
	for rows.Next() {
		var i ListEntitlementsWithBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.ResourceDomain,
			&i.ModelID,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.CreatedAt,
			&i.BalanceTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEvents = `-- name: ListLedgerEvents :many
SELECT id, user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by, created_at FROM ledger_events
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::uuid IS NULL OR entitlement_id = $2)
ORDER BY created_at DESC, id LIMIT $4 OFFSET $3
`

type ListLedgerEventsParams struct {
	UserID        *uuid.UUID `json:"user_id"`
	EntitlementID *uuid.UUID `json:"entitlement_id"`
	PageOffset    int32      `json:"page_offset"`
	PageSize      int32      `json:"page_size"`
}

func (q *Queries) ListLedgerEvents(ctx context.Context, arg ListLedgerEventsParams) ([]LedgerEvent, error) {
	rows, err := q.db.Query(ctx, listLedgerEvents,
		arg.UserID,
		arg.EntitlementID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntitlementID,
			&i.RequestID,
			&i.ReservationID,
			&i.Kind,
			&i.TokenDelta,
			&i.ReservedTokens,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.SourceEventID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsByEntitlement = `-- name: ListLedgerEventsByEntitlement :many
SELECT id, user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by, created_at FROM ledger_events WHERE entitlement_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListLedgerEventsByEntitlement(ctx context.Context, entitlementID uuid.UUID) ([]LedgerEvent, error) {
	rows, err := q.db.Query(ctx, listLedgerEventsByEntitlement, entitlementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntitlementID,
			&i.RequestID,
			&i.ReservationID,
			&i.Kind,
			&i.TokenDelta,
			&i.ReservedTokens,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.SourceEventID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestAttempts = `-- name: ListRequestAttempts :many
SELECT id, request_id, credential_id, sequence, status, upstream_request_id, http_status, error_kind, retry_after_at, sent_at, first_byte_at, completed_at, created_at FROM request_attempts WHERE request_id = $1 ORDER BY sequence, id
`

func (q *Queries) ListRequestAttempts(ctx context.Context, requestID uuid.UUID) ([]RequestAttempt, error) {
	rows, err := q.db.Query(ctx, listRequestAttempts, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestAttempt{}
	for rows.Next() {
		var i RequestAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.CredentialID,
			&i.Sequence,
			&i.Status,
			&i.UpstreamRequestID,
			&i.HttpStatus,
			&i.ErrorKind,
			&i.RetryAfterAt,
			&i.SentAt,
			&i.FirstByteAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests
WHERE ($1::uuid IS NULL OR user_id = $1)
ORDER BY accepted_at DESC, id LIMIT $3 OFFSET $2
`

type ListRequestsParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequests, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.UserID,
			&i.GatewayKeyID,
			&i.ModelID,
			&i.EntitlementID,
			&i.ConfigRevisionID,
			&i.ResourceDomain,
			&i.Status,
			&i.Stream,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.ErrorKind,
			&i.ErrorDetail,
			&i.AcceptedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserModelAuthorizations = `-- name: ListUserModelAuthorizations :many
SELECT a.user_id, a.model_id, a.created_at, m.public_name, m.display_name, m.resource_domain, m.enabled
FROM model_authorizations a
JOIN models m ON m.id = a.model_id
WHERE a.user_id = $1
ORDER BY m.public_name, m.id
`

type ListUserModelAuthorizationsRow struct {
	UserID         uuid.UUID          `json:"user_id"`
	ModelID        uuid.UUID          `json:"model_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PublicName     string             `json:"public_name"`
	DisplayName    string             `json:"display_name"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
	Enabled        bool               `json:"enabled"`
}

func (q *Queries) ListUserModelAuthorizations(ctx context.Context, userID uuid.UUID) ([]ListUserModelAuthorizationsRow, error) {
	rows, err := q.db.Query(ctx, listUserModelAuthorizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserModelAuthorizationsRow{}
	for rows.Next() {
		var i ListUserModelAuthorizationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ModelID,
			&i.CreatedAt,
			&i.PublicName,
			&i.DisplayName,
			&i.ResourceDomain,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestResponseCancellation = `-- name: RequestResponseCancellation :execrows
UPDATE response_records SET cancel_requested_at = now(), updated_at = now() WHERE id = $1 AND status IN ('queued','dispatching','streaming')
`

func (q *Queries) RequestResponseCancellation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requestResponseCancellation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAttempt = `-- name: UpdateAttempt :one
UPDATE request_attempts SET status = $1, upstream_request_id = $2, http_status = $3, error_kind = $4, retry_after_at = $5, sent_at = coalesce(sent_at, $6), first_byte_at = coalesce(first_byte_at, $7), completed_at = $8
WHERE id = $9 RETURNING id, request_id, credential_id, sequence, status, upstream_request_id, http_status, error_kind, retry_after_at, sent_at, first_byte_at, completed_at, created_at
`

type UpdateAttemptParams struct {
	Status            AttemptStatus      `json:"status"`
	UpstreamRequestID *string            `json:"upstream_request_id"`
	HttpStatus        *int32             `json:"http_status"`
	ErrorKind         *string            `json:"error_kind"`
	RetryAfterAt      pgtype.Timestamptz `json:"retry_after_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	FirstByteAt       pgtype.Timestamptz `json:"first_byte_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ID                uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) (RequestAttempt, error) {
	row := q.db.QueryRow(ctx, updateAttempt,
		arg.Status,
		arg.UpstreamRequestID,
		arg.HttpStatus,
		arg.ErrorKind,
		arg.RetryAfterAt,
		arg.SentAt,
		arg.FirstByteAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i RequestAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CredentialID,
		&i.Sequence,
		&i.Status,
		&i.UpstreamRequestID,
		&i.HttpStatus,
		&i.ErrorKind,
		&i.RetryAfterAt,
		&i.SentAt,
		&i.FirstByteAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :one
UPDATE requests SET status = $1, error_kind = $2, error_detail = $3, updated_at = now(), completed_at = CASE WHEN $1::request_status IN ('completed','failed','canceled','uncertain') THEN now() ELSE completed_at END
WHERE id = $4 RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, status, stream, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type UpdateRequestStatusParams struct {
	Status      RequestStatus `json:"status"`
	ErrorKind   *string       `json:"error_kind"`
	ErrorDetail *string       `json:"error_detail"`
	ID          uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStatus,
		arg.Status,
		arg.ErrorKind,
		arg.ErrorDetail,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.Status,
		&i.Stream,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResponseRecord = `-- name: UpdateResponseRecord :one
UPDATE response_records SET status = $1, output = $2, error = $3, updated_at = now() WHERE id = $4 RETURNING id, request_id, status, output, error, cancel_requested_at, created_at, updated_at
`

type UpdateResponseRecordParams struct {
	Status RequestStatus `json:"status"`
	Output []byte        `json:"output"`
	Error  []byte        `json:"error"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateResponseRecord(ctx context.Context, arg UpdateResponseRecordParams) (ResponseRecord, error) {
	row := q.db.QueryRow(ctx, updateResponseRecord,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.ID,
	)
	var i ResponseRecord
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Status,
		&i.Output,
		&i.Error,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
