// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimRequestExecution = `-- name: ClaimRequestExecution :one
UPDATE requests
SET status = 'dispatching',
    execution_id = $1,
    execution_generation = CASE WHEN execution_id IS NULL THEN execution_generation + 1 ELSE execution_generation END,
    execution_claimed_at = CASE WHEN execution_id IS NULL THEN now() ELSE execution_claimed_at END,
    execution_heartbeat_at = now(),
    updated_at = now()
WHERE id = $2
  AND (
      (status = 'queued' AND execution_id IS NULL)
      OR
      (status = 'dispatching' AND execution_id = $1)
  )
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type ClaimRequestExecutionParams struct {
	ExecutionID *uuid.UUID `json:"execution_id"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) ClaimRequestExecution(ctx context.Context, arg ClaimRequestExecutionParams) (Request, error) {
	row := q.db.QueryRow(ctx, claimRequestExecution, arg.ExecutionID, arg.ID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeLedgerReservation = `-- name: CompleteLedgerReservation :one
UPDATE ledger_reservations
SET state = $1, charged_tokens = $2, usage_source = $3, terminal_event_id = $4, updated_at = now()
WHERE id = $5 AND state = 'reserved'
RETURNING id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at
`

type CompleteLedgerReservationParams struct {
	State           ReservationState `json:"state"`
	ChargedTokens   int64            `json:"charged_tokens"`
	UsageSource     UsageSource      `json:"usage_source"`
	TerminalEventID *uuid.UUID       `json:"terminal_event_id"`
	ID              uuid.UUID        `json:"id"`
}

func (q *Queries) CompleteLedgerReservation(ctx context.Context, arg CompleteLedgerReservationParams) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, completeLedgerReservation,
		arg.State,
		arg.ChargedTokens,
		arg.UsageSource,
		arg.TerminalEventID,
		arg.ID,
	)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRequest = `-- name: CompleteRequest :one
UPDATE requests SET status = 'completed', input_tokens = $1, output_tokens = $2, usage_source = $3,
    input_cost_nanos = $4, output_cost_nanos = $5, total_cost_nanos = $6,
    error_kind = NULL, error_detail = NULL, completed_at = now(), updated_at = now()
WHERE id = $7
  AND execution_id = $8
  AND execution_generation = $9
  AND status IN ('dispatching', 'streaming')
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type CompleteRequestParams struct {
	InputTokens         *int64      `json:"input_tokens"`
	OutputTokens        *int64      `json:"output_tokens"`
	UsageSource         UsageSource `json:"usage_source"`
	InputCostNanos      *int64      `json:"input_cost_nanos"`
	OutputCostNanos     *int64      `json:"output_cost_nanos"`
	TotalCostNanos      *int64      `json:"total_cost_nanos"`
	ID                  uuid.UUID   `json:"id"`
	ExecutionID         *uuid.UUID  `json:"execution_id"`
	ExecutionGeneration int64       `json:"execution_generation"`
}

func (q *Queries) CompleteRequest(ctx context.Context, arg CompleteRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, completeRequest,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.InputCostNanos,
		arg.OutputCostNanos,
		arg.TotalCostNanos,
		arg.ID,
		arg.ExecutionID,
		arg.ExecutionGeneration,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countEntitlements = `-- name: CountEntitlements :one
SELECT count(*)
FROM entitlements e
JOIN users owner ON owner.id = e.user_id
LEFT JOIN models model ON model.id = e.model_id
WHERE ($1::uuid IS NULL OR e.user_id = $1)
  AND ($2::text = '' OR concat_ws(' ', owner.display_name, owner.email, model.public_name, e.plan::text, e.resource_domain::text) ILIKE '%' || $2::text || '%')
  AND ($3::text = ''
    OR $3::text = 'scheduled' AND e.starts_at > now()
    OR $3::text = 'active' AND e.starts_at <= now() AND e.expires_at > now()
    OR $3::text = 'expired' AND e.expires_at <= now())
  AND ($4::text = '' OR e.resource_domain::text = $4::text)
`

type CountEntitlementsParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	Search         string     `json:"search"`
	Status         string     `json:"status"`
	ResourceDomain string     `json:"resource_domain"`
}

func (q *Queries) CountEntitlements(ctx context.Context, arg CountEntitlementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitlements,
		arg.UserID,
		arg.Search,
		arg.Status,
		arg.ResourceDomain,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedgerEvents = `-- name: CountLedgerEvents :one
SELECT count(*)
FROM ledger_events event
JOIN users owner ON owner.id = event.user_id
JOIN entitlements entitlement ON entitlement.id = event.entitlement_id
LEFT JOIN users actor ON actor.id = event.created_by
WHERE ($1::uuid IS NULL OR event.user_id = $1)
  AND ($2::uuid IS NULL OR event.entitlement_id = $2)
  AND ($3::text = '' OR concat_ws(' ', owner.display_name, owner.email, actor.display_name, actor.email, event.note, event.request_id::text) ILIKE '%' || $3::text || '%')
  AND ($4::text = '' OR entitlement.resource_domain::text = $4::text)
`

type CountLedgerEventsParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	EntitlementID  *uuid.UUID `json:"entitlement_id"`
	Search         string     `json:"search"`
	ResourceDomain string     `json:"resource_domain"`
}

func (q *Queries) CountLedgerEvents(ctx context.Context, arg CountLedgerEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerEvents,
		arg.UserID,
		arg.EntitlementID,
		arg.Search,
		arg.ResourceDomain,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestUsage = `-- name: CountRequestUsage :one
SELECT count(*)
FROM requests AS request
JOIN users AS owner ON owner.id = request.user_id
JOIN gateway_keys AS key ON key.id = request.gateway_key_id
JOIN config_revision_models AS model
  ON model.revision_id = request.config_revision_id AND model.model_id = request.model_id
WHERE ($1::uuid IS NULL OR request.user_id = $1)
  AND request.input_tokens IS NOT NULL
  AND request.output_tokens IS NOT NULL
  AND request.usage_source IN ('authoritative', 'estimated')
  AND request.completed_at IS NOT NULL
  AND ($2::text = '' OR concat_ws(' ', owner.display_name, owner.email, key.prefix, model.public_name, request.id::text) ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR request.resource_domain::text = $3::text)
`

type CountRequestUsageParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	Search         string     `json:"search"`
	ResourceDomain string     `json:"resource_domain"`
}

func (q *Queries) CountRequestUsage(ctx context.Context, arg CountRequestUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestUsage, arg.UserID, arg.Search, arg.ResourceDomain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO request_attempts (request_id, execution_id, execution_generation, credential_id, sequence, status)
SELECT $1, $2, $3, $4, $5, $6
FROM requests
WHERE id = $1
  AND execution_id = $2
  AND execution_generation = $3
  AND status IN ('dispatching', 'streaming')
RETURNING id, request_id, execution_id, execution_generation, credential_id, sequence, status, upstream_request_id, http_status, error_kind, retry_after_at, sent_at, first_byte_at, completed_at, input_tokens, output_tokens, usage_source, created_at
`

type CreateAttemptParams struct {
	RequestID           uuid.UUID     `json:"request_id"`
	ExecutionID         uuid.UUID     `json:"execution_id"`
	ExecutionGeneration int64         `json:"execution_generation"`
	CredentialID        uuid.UUID     `json:"credential_id"`
	Sequence            int32         `json:"sequence"`
	Status              AttemptStatus `json:"status"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (RequestAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.RequestID,
		arg.ExecutionID,
		arg.ExecutionGeneration,
		arg.CredentialID,
		arg.Sequence,
		arg.Status,
	)
	var i RequestAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.CredentialID,
		&i.Sequence,
		&i.Status,
		&i.UpstreamRequestID,
		&i.HttpStatus,
		&i.ErrorKind,
		&i.RetryAfterAt,
		&i.SentAt,
		&i.FirstByteAt,
		&i.CompletedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.CreatedAt,
	)
	return i, err
}

const createEntitlement = `-- name: CreateEntitlement :one
INSERT INTO entitlements (user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at
`

type CreateEntitlementParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
}

func (q *Queries) CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, createEntitlement,
		arg.UserID,
		arg.Plan,
		arg.ResourceDomain,
		arg.ModelID,
		arg.GrantedTokens,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.ConcurrencyLimit,
		arg.RpmLimit,
		arg.TpmLimit,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.ResourceDomain,
		&i.ModelID,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEvent = `-- name: CreateLedgerEvent :one
INSERT INTO ledger_events (user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by, created_at
`

type CreateLedgerEventParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	EntitlementID  uuid.UUID       `json:"entitlement_id"`
	RequestID      *uuid.UUID      `json:"request_id"`
	ReservationID  *uuid.UUID      `json:"reservation_id"`
	Kind           LedgerEventKind `json:"kind"`
	TokenDelta     int64           `json:"token_delta"`
	ReservedTokens int64           `json:"reserved_tokens"`
	InputTokens    int64           `json:"input_tokens"`
	OutputTokens   int64           `json:"output_tokens"`
	UsageSource    UsageSource     `json:"usage_source"`
	SourceEventID  *uuid.UUID      `json:"source_event_id"`
	Note           *string         `json:"note"`
	CreatedBy      *uuid.UUID      `json:"created_by"`
}

func (q *Queries) CreateLedgerEvent(ctx context.Context, arg CreateLedgerEventParams) (LedgerEvent, error) {
	row := q.db.QueryRow(ctx, createLedgerEvent,
		arg.UserID,
		arg.EntitlementID,
		arg.RequestID,
		arg.ReservationID,
		arg.Kind,
		arg.TokenDelta,
		arg.ReservedTokens,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.SourceEventID,
		arg.Note,
		arg.CreatedBy,
	)
	var i LedgerEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntitlementID,
		&i.RequestID,
		&i.ReservationID,
		&i.Kind,
		&i.TokenDelta,
		&i.ReservedTokens,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.SourceEventID,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerReservation = `-- name: CreateLedgerReservation :one
INSERT INTO ledger_reservations (id, entitlement_id, request_id, state, reserved_tokens, reserve_event_id)
VALUES ($1, $2, $3, 'reserved', $4, $5)
RETURNING id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at
`

type CreateLedgerReservationParams struct {
	ID             uuid.UUID `json:"id"`
	EntitlementID  uuid.UUID `json:"entitlement_id"`
	RequestID      uuid.UUID `json:"request_id"`
	ReservedTokens int64     `json:"reserved_tokens"`
	ReserveEventID uuid.UUID `json:"reserve_event_id"`
}

func (q *Queries) CreateLedgerReservation(ctx context.Context, arg CreateLedgerReservationParams) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, createLedgerReservation,
		arg.ID,
		arg.EntitlementID,
		arg.RequestID,
		arg.ReservedTokens,
		arg.ReserveEventID,
	)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain,
                      price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, status, stream)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15)
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type CreateRequestParams struct {
	ID                        uuid.UUID      `json:"id"`
	IdempotencyKey            *string        `json:"idempotency_key"`
	RequestDigest             []byte         `json:"request_digest"`
	UserID                    uuid.UUID      `json:"user_id"`
	GatewayKeyID              uuid.UUID      `json:"gateway_key_id"`
	ModelID                   uuid.UUID      `json:"model_id"`
	EntitlementID             uuid.UUID      `json:"entitlement_id"`
	ConfigRevisionID          *uuid.UUID     `json:"config_revision_id"`
	ResourceDomain            ResourceDomain `json:"resource_domain"`
	PriceVersionID            uuid.UUID      `json:"price_version_id"`
	CostCurrency              string         `json:"cost_currency"`
	InputRateNanosPerMillion  int64          `json:"input_rate_nanos_per_million"`
	OutputRateNanosPerMillion int64          `json:"output_rate_nanos_per_million"`
	Status                    RequestStatus  `json:"status"`
	Stream                    bool           `json:"stream"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.UserID,
		arg.GatewayKeyID,
		arg.ModelID,
		arg.EntitlementID,
		arg.ConfigRevisionID,
		arg.ResourceDomain,
		arg.PriceVersionID,
		arg.CostCurrency,
		arg.InputRateNanosPerMillion,
		arg.OutputRateNanosPerMillion,
		arg.Status,
		arg.Stream,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const entitlementBalance = `-- name: EntitlementBalance :one
SELECT coalesce(sum(token_delta), 0)::bigint FROM ledger_events WHERE entitlement_id = $1
`

func (q *Queries) EntitlementBalance(ctx context.Context, entitlementID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, entitlementBalance, entitlementID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const failRequest = `-- name: FailRequest :one
UPDATE requests
SET status = 'failed', error_kind = $1, error_detail = $2, completed_at = now(), updated_at = now()
WHERE id = $3
  AND status IN ('queued', 'dispatching', 'streaming')
  AND (
      ($4::uuid IS NULL AND execution_id IS NULL AND execution_generation = 0)
      OR
      (execution_id = $4 AND execution_generation = $5)
  )
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type FailRequestParams struct {
	ErrorKind           *string    `json:"error_kind"`
	ErrorDetail         *string    `json:"error_detail"`
	ID                  uuid.UUID  `json:"id"`
	ExecutionID         *uuid.UUID `json:"execution_id"`
	ExecutionGeneration int64      `json:"execution_generation"`
}

func (q *Queries) FailRequest(ctx context.Context, arg FailRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, failRequest,
		arg.ErrorKind,
		arg.ErrorDetail,
		arg.ID,
		arg.ExecutionID,
		arg.ExecutionGeneration,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failRequestWithUsage = `-- name: FailRequestWithUsage :one
UPDATE requests
SET status = 'failed', input_tokens = $1, output_tokens = $2, usage_source = $3,
    input_cost_nanos = $4, output_cost_nanos = $5, total_cost_nanos = $6,
    error_kind = $7, error_detail = $8, completed_at = now(), updated_at = now()
WHERE id = $9
  AND execution_id = $10
  AND execution_generation = $11
  AND status IN ('dispatching', 'streaming')
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type FailRequestWithUsageParams struct {
	InputTokens         *int64      `json:"input_tokens"`
	OutputTokens        *int64      `json:"output_tokens"`
	UsageSource         UsageSource `json:"usage_source"`
	InputCostNanos      *int64      `json:"input_cost_nanos"`
	OutputCostNanos     *int64      `json:"output_cost_nanos"`
	TotalCostNanos      *int64      `json:"total_cost_nanos"`
	ErrorKind           *string     `json:"error_kind"`
	ErrorDetail         *string     `json:"error_detail"`
	ID                  uuid.UUID   `json:"id"`
	ExecutionID         *uuid.UUID  `json:"execution_id"`
	ExecutionGeneration int64       `json:"execution_generation"`
}

func (q *Queries) FailRequestWithUsage(ctx context.Context, arg FailRequestWithUsageParams) (Request, error) {
	row := q.db.QueryRow(ctx, failRequestWithUsage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.InputCostNanos,
		arg.OutputCostNanos,
		arg.TotalCostNanos,
		arg.ErrorKind,
		arg.ErrorDetail,
		arg.ID,
		arg.ExecutionID,
		arg.ExecutionGeneration,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveGatewayKeyForRequest = `-- name: GetActiveGatewayKeyForRequest :one
SELECT k.user_id
FROM gateway_keys k
JOIN users u ON u.id = k.user_id
WHERE k.id = $1
  AND k.user_id = $2
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
  AND u.status = 'active'
FOR SHARE OF k, u
`

type GetActiveGatewayKeyForRequestParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveGatewayKeyForRequest(ctx context.Context, arg GetActiveGatewayKeyForRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveGatewayKeyForRequest, arg.GatewayKeyID, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getAuthorizedGatewayKeyModelDomain = `-- name: GetAuthorizedGatewayKeyModelDomain :one
SELECT model.resource_domain
FROM config_revision_models model
JOIN config_revisions revision ON revision.id = model.revision_id
JOIN gateway_key_models key_model
  ON key_model.model_id = model.model_id AND key_model.gateway_key_id = $1
WHERE model.revision_id = $2
  AND model.model_id = $3
  AND revision.published_at IS NOT NULL
`

type GetAuthorizedGatewayKeyModelDomainParams struct {
	GatewayKeyID uuid.UUID `json:"gateway_key_id"`
	RevisionID   uuid.UUID `json:"revision_id"`
	ModelID      uuid.UUID `json:"model_id"`
}

func (q *Queries) GetAuthorizedGatewayKeyModelDomain(ctx context.Context, arg GetAuthorizedGatewayKeyModelDomainParams) (ResourceDomain, error) {
	row := q.db.QueryRow(ctx, getAuthorizedGatewayKeyModelDomain, arg.GatewayKeyID, arg.RevisionID, arg.ModelID)
	var resource_domain ResourceDomain
	err := row.Scan(&resource_domain)
	return resource_domain, err
}

const getEntitlementByGrantIdempotency = `-- name: GetEntitlementByGrantIdempotency :one
SELECT e.id, e.user_id, e.plan, e.resource_domain, e.model_id, e.granted_tokens, e.starts_at, e.expires_at, e.concurrency_limit, e.rpm_limit, e.tpm_limit, e.created_at, le.note AS grant_note
FROM ledger_events le
JOIN entitlements e ON e.id = le.entitlement_id
WHERE le.source_event_id = $1
  AND le.kind = 'grant'
  AND le.created_by = $2
`

type GetEntitlementByGrantIdempotencyParams struct {
	SourceEventID *uuid.UUID `json:"source_event_id"`
	CreatedBy     *uuid.UUID `json:"created_by"`
}

type GetEntitlementByGrantIdempotencyRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	GrantNote        *string            `json:"grant_note"`
}

func (q *Queries) GetEntitlementByGrantIdempotency(ctx context.Context, arg GetEntitlementByGrantIdempotencyParams) (GetEntitlementByGrantIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getEntitlementByGrantIdempotency, arg.SourceEventID, arg.CreatedBy)
	var i GetEntitlementByGrantIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.ResourceDomain,
		&i.ModelID,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedAt,
		&i.GrantNote,
	)
	return i, err
}

const getEntitlementForUpdate = `-- name: GetEntitlementForUpdate :one
SELECT id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at FROM entitlements WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetEntitlementForUpdate(ctx context.Context, id uuid.UUID) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlementForUpdate, id)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.ResourceDomain,
		&i.ModelID,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerReservationByRequest = `-- name: GetLedgerReservationByRequest :one
SELECT id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at FROM ledger_reservations WHERE request_id = $1
`

func (q *Queries) GetLedgerReservationByRequest(ctx context.Context, requestID uuid.UUID) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, getLedgerReservationByRequest, requestID)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerReservationByRequestForUpdate = `-- name: GetLedgerReservationByRequestForUpdate :one
SELECT id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at FROM ledger_reservations WHERE request_id = $1 FOR UPDATE
`

func (q *Queries) GetLedgerReservationByRequestForUpdate(ctx context.Context, requestID uuid.UUID) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, getLedgerReservationByRequestForUpdate, requestID)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerReservationForUpdate = `-- name: GetLedgerReservationForUpdate :one
SELECT id, entitlement_id, request_id, state, reserved_tokens, charged_tokens, usage_source, reserve_event_id, terminal_event_id, created_at, updated_at FROM ledger_reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetLedgerReservationForUpdate(ctx context.Context, id uuid.UUID) (LedgerReservation, error) {
	row := q.db.QueryRow(ctx, getLedgerReservationForUpdate, id)
	var i LedgerReservation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.RequestID,
		&i.State,
		&i.ReservedTokens,
		&i.ChargedTokens,
		&i.UsageSource,
		&i.ReserveEventID,
		&i.TerminalEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelDomain = `-- name: GetModelDomain :one
SELECT resource_domain FROM models WHERE id = $1
`

func (q *Queries) GetModelDomain(ctx context.Context, modelID uuid.UUID) (ResourceDomain, error) {
	row := q.db.QueryRow(ctx, getModelDomain, modelID)
	var resource_domain ResourceDomain
	err := row.Scan(&resource_domain)
	return resource_domain, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestByIdempotencyKey = `-- name: GetRequestByIdempotencyKey :one
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests WHERE gateway_key_id = $1 AND idempotency_key = $2
`

type GetRequestByIdempotencyKeyParams struct {
	GatewayKeyID   uuid.UUID `json:"gateway_key_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetRequestByIdempotencyKey(ctx context.Context, arg GetRequestByIdempotencyKeyParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByIdempotencyKey, arg.GatewayKeyID, arg.IdempotencyKey)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestForUpdate = `-- name: GetRequestForUpdate :one
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRequestForUpdate(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestForUpdate, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatRequestExecution = `-- name: HeartbeatRequestExecution :one
UPDATE requests
SET execution_heartbeat_at = now(), updated_at = now()
WHERE id = $1
  AND execution_id = $2
  AND execution_generation = $3
  AND status IN ('dispatching', 'streaming')
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type HeartbeatRequestExecutionParams struct {
	ID                  uuid.UUID  `json:"id"`
	ExecutionID         *uuid.UUID `json:"execution_id"`
	ExecutionGeneration int64      `json:"execution_generation"`
}

func (q *Queries) HeartbeatRequestExecution(ctx context.Context, arg HeartbeatRequestExecutionParams) (Request, error) {
	row := q.db.QueryRow(ctx, heartbeatRequestExecution, arg.ID, arg.ExecutionID, arg.ExecutionGeneration)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveEntitlements = `-- name: ListActiveEntitlements :many
SELECT id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at FROM entitlements WHERE user_id = $1 AND starts_at <= now() AND expires_at > now() ORDER BY resource_domain, expires_at, id
`

func (q *Queries) ListActiveEntitlements(ctx context.Context, userID uuid.UUID) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listActiveEntitlements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.ResourceDomain,
			&i.ModelID,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicableEntitlementsForUpdate = `-- name: ListApplicableEntitlementsForUpdate :many
SELECT id, user_id, plan, resource_domain, model_id, granted_tokens, starts_at, expires_at, concurrency_limit, rpm_limit, tpm_limit, created_at FROM entitlements
WHERE user_id = $1
  AND resource_domain = $2
  AND starts_at <= now() AND expires_at > now()
  AND (model_id IS NULL OR model_id = $3)
ORDER BY (model_id IS NOT NULL) DESC, expires_at, id
FOR UPDATE
`

type ListApplicableEntitlementsForUpdateParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	ResourceDomain ResourceDomain `json:"resource_domain"`
	ModelID        *uuid.UUID     `json:"model_id"`
}

func (q *Queries) ListApplicableEntitlementsForUpdate(ctx context.Context, arg ListApplicableEntitlementsForUpdateParams) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listApplicableEntitlementsForUpdate, arg.UserID, arg.ResourceDomain, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.ResourceDomain,
			&i.ModelID,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitlementsWithBalance = `-- name: ListEntitlementsWithBalance :many
SELECT e.id, e.user_id, e.plan, e.resource_domain, e.model_id, e.granted_tokens, e.starts_at, e.expires_at, e.concurrency_limit, e.rpm_limit, e.tpm_limit, e.created_at, coalesce(sum(le.token_delta), 0)::bigint AS balance_tokens
FROM entitlements e
JOIN users owner ON owner.id = e.user_id
LEFT JOIN models model ON model.id = e.model_id
LEFT JOIN ledger_events le ON le.entitlement_id = e.id
WHERE ($1::uuid IS NULL OR e.user_id = $1)
  AND ($2::text = '' OR concat_ws(' ', owner.display_name, owner.email, model.public_name, e.plan::text, e.resource_domain::text) ILIKE '%' || $2::text || '%')
  AND ($3::text = ''
    OR $3::text = 'scheduled' AND e.starts_at > now()
    OR $3::text = 'active' AND e.starts_at <= now() AND e.expires_at > now()
    OR $3::text = 'expired' AND e.expires_at <= now())
  AND ($4::text = '' OR e.resource_domain::text = $4::text)
GROUP BY e.id
ORDER BY e.created_at DESC, e.id
LIMIT $6 OFFSET $5
`

type ListEntitlementsWithBalanceParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	Search         string     `json:"search"`
	Status         string     `json:"status"`
	ResourceDomain string     `json:"resource_domain"`
	PageOffset     int32      `json:"page_offset"`
	PageSize       int32      `json:"page_size"`
}

type ListEntitlementsWithBalanceRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BalanceTokens    int64              `json:"balance_tokens"`
}

func (q *Queries) ListEntitlementsWithBalance(ctx context.Context, arg ListEntitlementsWithBalanceParams) ([]ListEntitlementsWithBalanceRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementsWithBalance,
		arg.UserID,
		arg.Search,
		arg.Status,
		arg.ResourceDomain,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitlementsWithBalanceRow{}
	for rows.Next() {
		var i ListEntitlementsWithBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Plan,
			&i.ResourceDomain,
			&i.ModelID,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.CreatedAt,
			&i.BalanceTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEvents = `-- name: ListLedgerEvents :many
SELECT event.id, event.user_id, event.entitlement_id, event.request_id, event.reservation_id, event.kind, event.token_delta, event.reserved_tokens, event.input_tokens, event.output_tokens, event.usage_source, event.source_event_id, event.note, event.created_by, event.created_at, entitlement.resource_domain
FROM ledger_events event
JOIN users owner ON owner.id = event.user_id
JOIN entitlements entitlement ON entitlement.id = event.entitlement_id
LEFT JOIN users actor ON actor.id = event.created_by
WHERE ($1::uuid IS NULL OR event.user_id = $1)
  AND ($2::uuid IS NULL OR event.entitlement_id = $2)
  AND ($3::text = '' OR concat_ws(' ', owner.display_name, owner.email, actor.display_name, actor.email, event.note, event.request_id::text) ILIKE '%' || $3::text || '%')
  AND ($4::text = '' OR entitlement.resource_domain::text = $4::text)
ORDER BY event.created_at DESC, event.id LIMIT $6 OFFSET $5
`

type ListLedgerEventsParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	EntitlementID  *uuid.UUID `json:"entitlement_id"`
	Search         string     `json:"search"`
	ResourceDomain string     `json:"resource_domain"`
	PageOffset     int32      `json:"page_offset"`
	PageSize       int32      `json:"page_size"`
}

type ListLedgerEventsRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EntitlementID  uuid.UUID          `json:"entitlement_id"`
	RequestID      *uuid.UUID         `json:"request_id"`
	ReservationID  *uuid.UUID         `json:"reservation_id"`
	Kind           LedgerEventKind    `json:"kind"`
	TokenDelta     int64              `json:"token_delta"`
	ReservedTokens int64              `json:"reserved_tokens"`
	InputTokens    int64              `json:"input_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	UsageSource    UsageSource        `json:"usage_source"`
	SourceEventID  *uuid.UUID         `json:"source_event_id"`
	Note           *string            `json:"note"`
	CreatedBy      *uuid.UUID         `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
}

func (q *Queries) ListLedgerEvents(ctx context.Context, arg ListLedgerEventsParams) ([]ListLedgerEventsRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEvents,
		arg.UserID,
		arg.EntitlementID,
		arg.Search,
		arg.ResourceDomain,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEventsRow{}
	for rows.Next() {
		var i ListLedgerEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntitlementID,
			&i.RequestID,
			&i.ReservationID,
			&i.Kind,
			&i.TokenDelta,
			&i.ReservedTokens,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.SourceEventID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResourceDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEventsByEntitlement = `-- name: ListLedgerEventsByEntitlement :many
SELECT id, user_id, entitlement_id, request_id, reservation_id, kind, token_delta, reserved_tokens, input_tokens, output_tokens, usage_source, source_event_id, note, created_by, created_at FROM ledger_events WHERE entitlement_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListLedgerEventsByEntitlement(ctx context.Context, entitlementID uuid.UUID) ([]LedgerEvent, error) {
	rows, err := q.db.Query(ctx, listLedgerEventsByEntitlement, entitlementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEvent{}
	for rows.Next() {
		var i LedgerEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntitlementID,
			&i.RequestID,
			&i.ReservationID,
			&i.Kind,
			&i.TokenDelta,
			&i.ReservedTokens,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.SourceEventID,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoverableRequestSettlements = `-- name: ListRecoverableRequestSettlements :many
SELECT request.id AS request_id,
       request.execution_id,
       request.execution_generation,
       completed_attempt.input_tokens,
       completed_attempt.output_tokens,
       completed_attempt.usage_source
FROM requests AS request
JOIN ledger_reservations AS reservation
  ON reservation.request_id = request.id AND reservation.state = 'reserved'
JOIN LATERAL (
    SELECT attempt.input_tokens, attempt.output_tokens, attempt.usage_source
    FROM request_attempts AS attempt
    WHERE attempt.request_id = request.id
      AND attempt.execution_id = request.execution_id
      AND attempt.execution_generation = request.execution_generation
      AND attempt.status = 'completed'
      AND attempt.input_tokens IS NOT NULL
      AND attempt.output_tokens IS NOT NULL
      AND attempt.usage_source IN ('authoritative', 'estimated')
    ORDER BY attempt.sequence DESC
    LIMIT 1
) AS completed_attempt ON true
WHERE request.status IN ('dispatching', 'streaming')
  AND request.execution_id IS NOT NULL
  AND request.execution_heartbeat_at < $1
ORDER BY request.execution_heartbeat_at, request.id
LIMIT $2
`

type ListRecoverableRequestSettlementsParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	BatchSize   int32              `json:"batch_size"`
}

type ListRecoverableRequestSettlementsRow struct {
	RequestID           uuid.UUID   `json:"request_id"`
	ExecutionID         *uuid.UUID  `json:"execution_id"`
	ExecutionGeneration int64       `json:"execution_generation"`
	InputTokens         *int64      `json:"input_tokens"`
	OutputTokens        *int64      `json:"output_tokens"`
	UsageSource         UsageSource `json:"usage_source"`
}

func (q *Queries) ListRecoverableRequestSettlements(ctx context.Context, arg ListRecoverableRequestSettlementsParams) ([]ListRecoverableRequestSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listRecoverableRequestSettlements, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecoverableRequestSettlementsRow{}
	for rows.Next() {
		var i ListRecoverableRequestSettlementsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.ExecutionID,
			&i.ExecutionGeneration,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestAttempts = `-- name: ListRequestAttempts :many
SELECT id, request_id, execution_id, execution_generation, credential_id, sequence, status, upstream_request_id, http_status, error_kind, retry_after_at, sent_at, first_byte_at, completed_at, input_tokens, output_tokens, usage_source, created_at FROM request_attempts WHERE request_id = $1 ORDER BY sequence, id
`

func (q *Queries) ListRequestAttempts(ctx context.Context, requestID uuid.UUID) ([]RequestAttempt, error) {
	rows, err := q.db.Query(ctx, listRequestAttempts, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestAttempt{}
	for rows.Next() {
		var i RequestAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ExecutionID,
			&i.ExecutionGeneration,
			&i.CredentialID,
			&i.Sequence,
			&i.Status,
			&i.UpstreamRequestID,
			&i.HttpStatus,
			&i.ErrorKind,
			&i.RetryAfterAt,
			&i.SentAt,
			&i.FirstByteAt,
			&i.CompletedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestUsage = `-- name: ListRequestUsage :many
SELECT request.id, request.user_id, key.prefix AS key_prefix,
       model.public_name AS model_alias, request.resource_domain,
       request.input_tokens, request.output_tokens, request.usage_source, request.completed_at
FROM requests AS request
JOIN users AS owner ON owner.id = request.user_id
JOIN gateway_keys AS key ON key.id = request.gateway_key_id
JOIN config_revision_models AS model
  ON model.revision_id = request.config_revision_id AND model.model_id = request.model_id
WHERE ($1::uuid IS NULL OR request.user_id = $1)
  AND request.input_tokens IS NOT NULL
  AND request.output_tokens IS NOT NULL
  AND request.usage_source IN ('authoritative', 'estimated')
  AND request.completed_at IS NOT NULL
  AND ($2::text = '' OR concat_ws(' ', owner.display_name, owner.email, key.prefix, model.public_name, request.id::text) ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR request.resource_domain::text = $3::text)
ORDER BY request.completed_at DESC, request.id
LIMIT $5 OFFSET $4
`

type ListRequestUsageParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	Search         string     `json:"search"`
	ResourceDomain string     `json:"resource_domain"`
	PageOffset     int32      `json:"page_offset"`
	PageSize       int32      `json:"page_size"`
}

type ListRequestUsageRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	KeyPrefix      string             `json:"key_prefix"`
	ModelAlias     string             `json:"model_alias"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
	InputTokens    *int64             `json:"input_tokens"`
	OutputTokens   *int64             `json:"output_tokens"`
	UsageSource    UsageSource        `json:"usage_source"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListRequestUsage(ctx context.Context, arg ListRequestUsageParams) ([]ListRequestUsageRow, error) {
	rows, err := q.db.Query(ctx, listRequestUsage,
		arg.UserID,
		arg.Search,
		arg.ResourceDomain,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestUsageRow{}
	for rows.Next() {
		var i ListRequestUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyPrefix,
			&i.ModelAlias,
			&i.ResourceDomain,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at FROM requests
WHERE ($1::uuid IS NULL OR user_id = $1)
ORDER BY accepted_at DESC, id LIMIT $3 OFFSET $2
`

type ListRequestsParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequests, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.UserID,
			&i.GatewayKeyID,
			&i.ModelID,
			&i.EntitlementID,
			&i.ConfigRevisionID,
			&i.ResourceDomain,
			&i.PriceVersionID,
			&i.CostCurrency,
			&i.InputRateNanosPerMillion,
			&i.OutputRateNanosPerMillion,
			&i.InputCostNanos,
			&i.OutputCostNanos,
			&i.TotalCostNanos,
			&i.Status,
			&i.Stream,
			&i.ExecutionID,
			&i.ExecutionGeneration,
			&i.ExecutionClaimedAt,
			&i.ExecutionHeartbeatAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.UsageSource,
			&i.ErrorKind,
			&i.ErrorDetail,
			&i.AcceptedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleQueuedRequests = `-- name: ListStaleQueuedRequests :many
SELECT request.id
FROM requests AS request
JOIN ledger_reservations AS reservation
  ON reservation.request_id = request.id AND reservation.state = 'reserved'
WHERE request.status = 'queued'
  AND request.execution_id IS NULL
  AND request.execution_generation = 0
  AND request.updated_at < $1
ORDER BY request.updated_at, request.id
LIMIT $2
`

type ListStaleQueuedRequestsParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	BatchSize   int32              `json:"batch_size"`
}

func (q *Queries) ListStaleQueuedRequests(ctx context.Context, arg ListStaleQueuedRequestsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleQueuedRequests, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestExecutionStreaming = `-- name: MarkRequestExecutionStreaming :one
UPDATE requests
SET status = 'streaming', execution_heartbeat_at = now(), updated_at = now()
WHERE id = $1
  AND execution_id = $2
  AND execution_generation = $3
  AND status IN ('dispatching', 'streaming')
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type MarkRequestExecutionStreamingParams struct {
	ID                  uuid.UUID  `json:"id"`
	ExecutionID         *uuid.UUID `json:"execution_id"`
	ExecutionGeneration int64      `json:"execution_generation"`
}

func (q *Queries) MarkRequestExecutionStreaming(ctx context.Context, arg MarkRequestExecutionStreamingParams) (Request, error) {
	row := q.db.QueryRow(ctx, markRequestExecutionStreaming, arg.ID, arg.ExecutionID, arg.ExecutionGeneration)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRequestExecutionUncertain = `-- name: MarkRequestExecutionUncertain :one
UPDATE requests
SET status = 'uncertain', error_kind = $1, error_detail = $2,
    completed_at = now(), updated_at = now()
WHERE id = $3
  AND execution_id = $4
  AND execution_generation = $5
  AND status IN ('dispatching', 'streaming')
RETURNING id, idempotency_key, request_digest, user_id, gateway_key_id, model_id, entitlement_id, config_revision_id, resource_domain, price_version_id, cost_currency, input_rate_nanos_per_million, output_rate_nanos_per_million, input_cost_nanos, output_cost_nanos, total_cost_nanos, status, stream, execution_id, execution_generation, execution_claimed_at, execution_heartbeat_at, input_tokens, output_tokens, usage_source, error_kind, error_detail, accepted_at, completed_at, updated_at
`

type MarkRequestExecutionUncertainParams struct {
	ErrorKind           *string    `json:"error_kind"`
	ErrorDetail         *string    `json:"error_detail"`
	ID                  uuid.UUID  `json:"id"`
	ExecutionID         *uuid.UUID `json:"execution_id"`
	ExecutionGeneration int64      `json:"execution_generation"`
}

func (q *Queries) MarkRequestExecutionUncertain(ctx context.Context, arg MarkRequestExecutionUncertainParams) (Request, error) {
	row := q.db.QueryRow(ctx, markRequestExecutionUncertain,
		arg.ErrorKind,
		arg.ErrorDetail,
		arg.ID,
		arg.ExecutionID,
		arg.ExecutionGeneration,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.UserID,
		&i.GatewayKeyID,
		&i.ModelID,
		&i.EntitlementID,
		&i.ConfigRevisionID,
		&i.ResourceDomain,
		&i.PriceVersionID,
		&i.CostCurrency,
		&i.InputRateNanosPerMillion,
		&i.OutputRateNanosPerMillion,
		&i.InputCostNanos,
		&i.OutputCostNanos,
		&i.TotalCostNanos,
		&i.Status,
		&i.Stream,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.ExecutionClaimedAt,
		&i.ExecutionHeartbeatAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.ErrorKind,
		&i.ErrorDetail,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recoverStaleRequestExecutions = `-- name: RecoverStaleRequestExecutions :one
WITH stale AS (
    SELECT candidate.id, candidate.execution_id, candidate.execution_generation
    FROM requests AS candidate
    WHERE candidate.status IN ('dispatching', 'streaming')
      AND candidate.execution_heartbeat_at < $1
      AND NOT EXISTS (
          SELECT 1 FROM request_attempts completed_attempt
          WHERE completed_attempt.request_id = candidate.id
            AND completed_attempt.execution_id = candidate.execution_id
            AND completed_attempt.execution_generation = candidate.execution_generation
            AND completed_attempt.status = 'completed'
            AND completed_attempt.input_tokens IS NOT NULL
            AND completed_attempt.output_tokens IS NOT NULL
            AND completed_attempt.usage_source IN ('authoritative', 'estimated')
      )
    ORDER BY candidate.execution_heartbeat_at, candidate.id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
), fenced_attempts AS (
    UPDATE request_attempts AS attempt
    SET status = 'uncertain', error_kind = 'uncertain', completed_at = now()
    FROM stale
    WHERE attempt.request_id = stale.id
      AND attempt.execution_id = stale.execution_id
      AND attempt.execution_generation = stale.execution_generation
      AND attempt.status IN ('created', 'sending', 'streaming')
), fenced_requests AS (
    UPDATE requests AS request
    SET status = 'uncertain', error_kind = 'uncertain',
        error_detail = 'request execution heartbeat expired; upstream outcome requires recovery',
        completed_at = now(), updated_at = now()
    FROM stale
    WHERE request.id = stale.id
      AND request.execution_id = stale.execution_id
      AND request.execution_generation = stale.execution_generation
      AND request.status IN ('dispatching', 'streaming')
    RETURNING request.id
)
SELECT count(*)::bigint FROM fenced_requests
`

type RecoverStaleRequestExecutionsParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	BatchSize   int32              `json:"batch_size"`
}

func (q *Queries) RecoverStaleRequestExecutions(ctx context.Context, arg RecoverStaleRequestExecutionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, recoverStaleRequestExecutions, arg.StaleBefore, arg.BatchSize)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAttempt = `-- name: UpdateAttempt :one
UPDATE request_attempts AS attempt
SET status = $1, upstream_request_id = $2, http_status = $3,
    error_kind = $4, retry_after_at = $5,
    sent_at = coalesce(sent_at, $6), first_byte_at = coalesce(first_byte_at, $7),
    completed_at = $8, input_tokens = $9, output_tokens = $10,
    usage_source = $11
WHERE attempt.id = $12
  AND attempt.request_id = $13
  AND attempt.execution_id = $14
  AND attempt.execution_generation = $15
  AND EXISTS (
      SELECT 1 FROM requests request
      WHERE request.id = attempt.request_id
        AND request.execution_id = attempt.execution_id
        AND request.execution_generation = attempt.execution_generation
        AND request.status IN ('dispatching', 'streaming')
  )
  AND CASE $1::attempt_status
      WHEN 'sending' THEN attempt.status = 'created'
      WHEN 'streaming' THEN attempt.status IN ('sending', 'streaming')
      WHEN 'completed' THEN attempt.status IN ('sending', 'streaming')
      WHEN 'failed' THEN attempt.status IN ('created', 'sending', 'streaming')
      WHEN 'uncertain' THEN attempt.status IN ('created', 'sending', 'streaming')
      ELSE false
  END
RETURNING attempt.id, attempt.request_id, attempt.execution_id, attempt.execution_generation, attempt.credential_id, attempt.sequence, attempt.status, attempt.upstream_request_id, attempt.http_status, attempt.error_kind, attempt.retry_after_at, attempt.sent_at, attempt.first_byte_at, attempt.completed_at, attempt.input_tokens, attempt.output_tokens, attempt.usage_source, attempt.created_at
`

type UpdateAttemptParams struct {
	Status              AttemptStatus      `json:"status"`
	UpstreamRequestID   *string            `json:"upstream_request_id"`
	HttpStatus          *int32             `json:"http_status"`
	ErrorKind           *string            `json:"error_kind"`
	RetryAfterAt        pgtype.Timestamptz `json:"retry_after_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	FirstByteAt         pgtype.Timestamptz `json:"first_byte_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	InputTokens         *int64             `json:"input_tokens"`
	OutputTokens        *int64             `json:"output_tokens"`
	UsageSource         UsageSource        `json:"usage_source"`
	ID                  uuid.UUID          `json:"id"`
	RequestID           uuid.UUID          `json:"request_id"`
	ExecutionID         uuid.UUID          `json:"execution_id"`
	ExecutionGeneration int64              `json:"execution_generation"`
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) (RequestAttempt, error) {
	row := q.db.QueryRow(ctx, updateAttempt,
		arg.Status,
		arg.UpstreamRequestID,
		arg.HttpStatus,
		arg.ErrorKind,
		arg.RetryAfterAt,
		arg.SentAt,
		arg.FirstByteAt,
		arg.CompletedAt,
		arg.InputTokens,
		arg.OutputTokens,
		arg.UsageSource,
		arg.ID,
		arg.RequestID,
		arg.ExecutionID,
		arg.ExecutionGeneration,
	)
	var i RequestAttempt
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ExecutionID,
		&i.ExecutionGeneration,
		&i.CredentialID,
		&i.Sequence,
		&i.Status,
		&i.UpstreamRequestID,
		&i.HttpStatus,
		&i.ErrorKind,
		&i.RetryAfterAt,
		&i.SentAt,
		&i.FirstByteAt,
		&i.CompletedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.UsageSource,
		&i.CreatedAt,
	)
	return i, err
}
