// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptStatus string

const (
	AttemptStatusCreated   AttemptStatus = "created"
	AttemptStatusSending   AttemptStatus = "sending"
	AttemptStatusStreaming AttemptStatus = "streaming"
	AttemptStatusCompleted AttemptStatus = "completed"
	AttemptStatusFailed    AttemptStatus = "failed"
	AttemptStatusUncertain AttemptStatus = "uncertain"
)

func (e *AttemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptStatus(s)
	case string:
		*e = AttemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptStatus: %T", src)
	}
	return nil
}

type NullAttemptStatus struct {
	AttemptStatus AttemptStatus `json:"attempt_status"`
	Valid         bool          `json:"valid"` // Valid is true if AttemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptStatus), nil
}

type CredentialStatus string

const (
	CredentialStatusActive   CredentialStatus = "active"
	CredentialStatusCooling  CredentialStatus = "cooling"
	CredentialStatusDisabled CredentialStatus = "disabled"
)

func (e *CredentialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialStatus(s)
	case string:
		*e = CredentialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialStatus: %T", src)
	}
	return nil
}

type NullCredentialStatus struct {
	CredentialStatus CredentialStatus `json:"credential_status"`
	Valid            bool             `json:"valid"` // Valid is true if CredentialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialStatus), nil
}

type LedgerEventKind string

const (
	LedgerEventKindGrant        LedgerEventKind = "grant"
	LedgerEventKindReservation  LedgerEventKind = "reservation"
	LedgerEventKindSettlement   LedgerEventKind = "settlement"
	LedgerEventKindRelease      LedgerEventKind = "release"
	LedgerEventKindCompensation LedgerEventKind = "compensation"
	LedgerEventKindAdjustment   LedgerEventKind = "adjustment"
	LedgerEventKindExpiration   LedgerEventKind = "expiration"
)

func (e *LedgerEventKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEventKind(s)
	case string:
		*e = LedgerEventKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEventKind: %T", src)
	}
	return nil
}

type NullLedgerEventKind struct {
	LedgerEventKind LedgerEventKind `json:"ledger_event_kind"`
	Valid           bool            `json:"valid"` // Valid is true if LedgerEventKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEventKind) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEventKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEventKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEventKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEventKind), nil
}

type PlanKind string

const (
	PlanKindToken  PlanKind = "token"
	PlanKindCoding PlanKind = "coding"
)

func (e *PlanKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanKind(s)
	case string:
		*e = PlanKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanKind: %T", src)
	}
	return nil
}

type NullPlanKind struct {
	PlanKind PlanKind `json:"plan_kind"`
	Valid    bool     `json:"valid"` // Valid is true if PlanKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanKind) Scan(value interface{}) error {
	if value == nil {
		ns.PlanKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanKind), nil
}

type RequestStatus string

const (
	RequestStatusQueued      RequestStatus = "queued"
	RequestStatusDispatching RequestStatus = "dispatching"
	RequestStatusStreaming   RequestStatus = "streaming"
	RequestStatusCompleted   RequestStatus = "completed"
	RequestStatusFailed      RequestStatus = "failed"
	RequestStatusCanceled    RequestStatus = "canceled"
	RequestStatusUncertain   RequestStatus = "uncertain"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type ReservationState string

const (
	ReservationStateReserved    ReservationState = "reserved"
	ReservationStateSettled     ReservationState = "settled"
	ReservationStateReleased    ReservationState = "released"
	ReservationStateCompensated ReservationState = "compensated"
)

func (e *ReservationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationState(s)
	case string:
		*e = ReservationState(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationState: %T", src)
	}
	return nil
}

type NullReservationState struct {
	ReservationState ReservationState `json:"reservation_state"`
	Valid            bool             `json:"valid"` // Valid is true if ReservationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationState) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationState), nil
}

type ResourceDomain string

const (
	ResourceDomainFree         ResourceDomain = "free"
	ResourceDomainProfessional ResourceDomain = "professional"
)

func (e *ResourceDomain) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceDomain(s)
	case string:
		*e = ResourceDomain(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceDomain: %T", src)
	}
	return nil
}

type NullResourceDomain struct {
	ResourceDomain ResourceDomain `json:"resource_domain"`
	Valid          bool           `json:"valid"` // Valid is true if ResourceDomain is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceDomain) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceDomain, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceDomain.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceDomain) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceDomain), nil
}

type ResponseStatus string

const (
	ResponseStatusQueued     ResponseStatus = "queued"
	ResponseStatusInProgress ResponseStatus = "in_progress"
	ResponseStatusCompleted  ResponseStatus = "completed"
	ResponseStatusFailed     ResponseStatus = "failed"
	ResponseStatusCanceled   ResponseStatus = "canceled"
	ResponseStatusUncertain  ResponseStatus = "uncertain"
)

func (e *ResponseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResponseStatus(s)
	case string:
		*e = ResponseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResponseStatus: %T", src)
	}
	return nil
}

type NullResponseStatus struct {
	ResponseStatus ResponseStatus `json:"response_status"`
	Valid          bool           `json:"valid"` // Valid is true if ResponseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResponseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResponseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResponseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResponseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResponseStatus), nil
}

type UsageSource string

const (
	UsageSourceAuthoritative UsageSource = "authoritative"
	UsageSourceEstimated     UsageSource = "estimated"
	UsageSourceUnknown       UsageSource = "unknown"
)

func (e *UsageSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsageSource(s)
	case string:
		*e = UsageSource(s)
	default:
		return fmt.Errorf("unsupported scan type for UsageSource: %T", src)
	}
	return nil
}

type NullUsageSource struct {
	UsageSource UsageSource `json:"usage_source"`
	Valid       bool        `json:"valid"` // Valid is true if UsageSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsageSource) Scan(value interface{}) error {
	if value == nil {
		ns.UsageSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsageSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsageSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsageSource), nil
}

type UserRole string

const (
	UserRoleAdministrator UserRole = "administrator"
	UserRoleMember        UserRole = "member"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusPending  UserStatus = "pending"
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type ActiveConfig struct {
	Singleton  bool               `json:"singleton"`
	RevisionID uuid.UUID          `json:"revision_id"`
	Version    int64              `json:"version"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID          uuid.UUID          `json:"id"`
	ActorUserID *uuid.UUID         `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    *string            `json:"target_id"`
	RequestID   *string            `json:"request_id"`
	Detail      []byte             `json:"detail"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ConfigMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	Action             string             `json:"action"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	RevisionID         *uuid.UUID         `json:"revision_id"`
	Result             []byte             `json:"result"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ConfigRevision struct {
	ID          uuid.UUID          `json:"id"`
	Revision    *int64             `json:"revision"`
	Checksum    string             `json:"checksum"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	PublishedBy *uuid.UUID         `json:"published_by"`
}

type ConfigRevisionCredential struct {
	RevisionID       uuid.UUID      `json:"revision_id"`
	CredentialID     uuid.UUID      `json:"credential_id"`
	ProviderID       uuid.UUID      `json:"provider_id"`
	ResourceDomain   ResourceDomain `json:"resource_domain"`
	RpmLimit         *int32         `json:"rpm_limit"`
	TpmLimit         *int64         `json:"tpm_limit"`
	ConcurrencyLimit *int32         `json:"concurrency_limit"`
}

type ConfigRevisionModel struct {
	RevisionID     uuid.UUID          `json:"revision_id"`
	ModelID        uuid.UUID          `json:"model_id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	PublicName     string             `json:"public_name"`
	UpstreamName   string             `json:"upstream_name"`
	DisplayName    string             `json:"display_name"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
	Capabilities   []byte             `json:"capabilities"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ConfigRevisionProvider struct {
	RevisionID uuid.UUID `json:"revision_id"`
	ProviderID uuid.UUID `json:"provider_id"`
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	Kind       string    `json:"kind"`
	BaseUrl    string    `json:"base_url"`
}

type ConfigRevisionRoute struct {
	RevisionID   uuid.UUID `json:"revision_id"`
	ModelID      uuid.UUID `json:"model_id"`
	CredentialID uuid.UUID `json:"credential_id"`
	Priority     int32     `json:"priority"`
	Weight       int32     `json:"weight"`
}

type CredentialModel struct {
	CredentialID uuid.UUID `json:"credential_id"`
	ModelID      uuid.UUID `json:"model_id"`
	Priority     int32     `json:"priority"`
	Weight       int32     `json:"weight"`
}

type CredentialMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	Action             string             `json:"action"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	CredentialID       *uuid.UUID         `json:"credential_id"`
	Result             []byte             `json:"result"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Entitlement struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Plan             PlanKind           `json:"plan"`
	ResourceDomain   ResourceDomain     `json:"resource_domain"`
	ModelID          *uuid.UUID         `json:"model_id"`
	GrantedTokens    int64              `json:"granted_tokens"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConcurrencyLimit int32              `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type GatewayKey struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	SecretDigest []byte             `json:"secret_digest"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type GatewayKeyModel struct {
	GatewayKeyID uuid.UUID          `json:"gateway_key_id"`
	ModelID      uuid.UUID          `json:"model_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type GatewayKeyMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	GatewayKeyID       *uuid.UUID         `json:"gateway_key_id"`
	Result             []byte             `json:"result"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID         uuid.UUID          `json:"id"`
	CodeDigest []byte             `json:"code_digest"`
	CodePrefix string             `json:"code_prefix"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ClaimedBy  *uuid.UUID         `json:"claimed_by"`
	ClaimedAt  pgtype.Timestamptz `json:"claimed_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type InvitationMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	InvitationID       *uuid.UUID         `json:"invitation_id"`
	Result             []byte             `json:"result"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type LedgerEvent struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EntitlementID  uuid.UUID          `json:"entitlement_id"`
	RequestID      *uuid.UUID         `json:"request_id"`
	ReservationID  *uuid.UUID         `json:"reservation_id"`
	Kind           LedgerEventKind    `json:"kind"`
	TokenDelta     int64              `json:"token_delta"`
	ReservedTokens int64              `json:"reserved_tokens"`
	InputTokens    int64              `json:"input_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	UsageSource    UsageSource        `json:"usage_source"`
	SourceEventID  *uuid.UUID         `json:"source_event_id"`
	Note           *string            `json:"note"`
	CreatedBy      *uuid.UUID         `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LedgerReservation struct {
	ID              uuid.UUID          `json:"id"`
	EntitlementID   uuid.UUID          `json:"entitlement_id"`
	RequestID       uuid.UUID          `json:"request_id"`
	State           ReservationState   `json:"state"`
	ReservedTokens  int64              `json:"reserved_tokens"`
	ChargedTokens   int64              `json:"charged_tokens"`
	UsageSource     UsageSource        `json:"usage_source"`
	ReserveEventID  uuid.UUID          `json:"reserve_event_id"`
	TerminalEventID *uuid.UUID         `json:"terminal_event_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MemberPasswordResetMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	UserID             uuid.UUID          `json:"user_id"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	Result             []byte             `json:"result"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Model struct {
	ID             uuid.UUID          `json:"id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	PublicName     string             `json:"public_name"`
	UpstreamName   string             `json:"upstream_name"`
	DisplayName    string             `json:"display_name"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
	Capabilities   []byte             `json:"capabilities"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ModelPriceMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	PriceVersionID     *uuid.UUID         `json:"price_version_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ModelPriceVersion struct {
	ID                        uuid.UUID          `json:"id"`
	ModelID                   uuid.UUID          `json:"model_id"`
	Currency                  string             `json:"currency"`
	InputRateNanosPerMillion  int64              `json:"input_rate_nanos_per_million"`
	OutputRateNanosPerMillion int64              `json:"output_rate_nanos_per_million"`
	EffectiveAt               pgtype.Timestamptz `json:"effective_at"`
	CreatedBy                 uuid.UUID          `json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	ID         uuid.UUID          `json:"id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	BaseUrl    string             `json:"base_url"`
	Enabled    bool               `json:"enabled"`
	SourceUrl  *string            `json:"source_url"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProviderCredential struct {
	ID                  uuid.UUID          `json:"id"`
	ProviderID          uuid.UUID          `json:"provider_id"`
	Name                string             `json:"name"`
	EncryptedSecret     []byte             `json:"encrypted_secret"`
	ResourceDomain      ResourceDomain     `json:"resource_domain"`
	Status              CredentialStatus   `json:"status"`
	RpmLimit            *int32             `json:"rpm_limit"`
	TpmLimit            *int64             `json:"tpm_limit"`
	ConcurrencyLimit    *int32             `json:"concurrency_limit"`
	CooldownUntil       pgtype.Timestamptz `json:"cooldown_until"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastErrorKind       *string            `json:"last_error_kind"`
	LastProbeAt         pgtype.Timestamptz `json:"last_probe_at"`
	LastProbeLatencyMs  *int64             `json:"last_probe_latency_ms"`
	LastProbeKind       *string            `json:"last_probe_kind"`
	LastProbeStatus     *string            `json:"last_probe_status"`
	LastProbeErrorKind  *string            `json:"last_probe_error_kind"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ProviderMutation struct {
	ID                 uuid.UUID          `json:"id"`
	ActorUserID        uuid.UUID          `json:"actor_user_id"`
	Action             string             `json:"action"`
	IdempotencyKey     uuid.UUID          `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	RequestID          string             `json:"request_id"`
	ProviderID         *uuid.UUID         `json:"provider_id"`
	Result             []byte             `json:"result"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Request struct {
	ID                        uuid.UUID          `json:"id"`
	IdempotencyKey            *string            `json:"idempotency_key"`
	RequestDigest             []byte             `json:"request_digest"`
	UserID                    uuid.UUID          `json:"user_id"`
	GatewayKeyID              uuid.UUID          `json:"gateway_key_id"`
	ModelID                   uuid.UUID          `json:"model_id"`
	EntitlementID             uuid.UUID          `json:"entitlement_id"`
	ConfigRevisionID          *uuid.UUID         `json:"config_revision_id"`
	ResourceDomain            ResourceDomain     `json:"resource_domain"`
	PriceVersionID            uuid.UUID          `json:"price_version_id"`
	CostCurrency              string             `json:"cost_currency"`
	InputRateNanosPerMillion  int64              `json:"input_rate_nanos_per_million"`
	OutputRateNanosPerMillion int64              `json:"output_rate_nanos_per_million"`
	InputCostNanos            *int64             `json:"input_cost_nanos"`
	OutputCostNanos           *int64             `json:"output_cost_nanos"`
	TotalCostNanos            *int64             `json:"total_cost_nanos"`
	Status                    RequestStatus      `json:"status"`
	Stream                    bool               `json:"stream"`
	ExecutionID               *uuid.UUID         `json:"execution_id"`
	ExecutionGeneration       int64              `json:"execution_generation"`
	ExecutionClaimedAt        pgtype.Timestamptz `json:"execution_claimed_at"`
	ExecutionHeartbeatAt      pgtype.Timestamptz `json:"execution_heartbeat_at"`
	InputTokens               *int64             `json:"input_tokens"`
	OutputTokens              *int64             `json:"output_tokens"`
	UsageSource               UsageSource        `json:"usage_source"`
	ErrorKind                 *string            `json:"error_kind"`
	ErrorDetail               *string            `json:"error_detail"`
	AcceptedAt                pgtype.Timestamptz `json:"accepted_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type RequestAttempt struct {
	ID                  uuid.UUID          `json:"id"`
	RequestID           uuid.UUID          `json:"request_id"`
	ExecutionID         uuid.UUID          `json:"execution_id"`
	ExecutionGeneration int64              `json:"execution_generation"`
	CredentialID        uuid.UUID          `json:"credential_id"`
	Sequence            int32              `json:"sequence"`
	Status              AttemptStatus      `json:"status"`
	UpstreamRequestID   *string            `json:"upstream_request_id"`
	HttpStatus          *int32             `json:"http_status"`
	ErrorKind           *string            `json:"error_kind"`
	RetryAfterAt        pgtype.Timestamptz `json:"retry_after_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	FirstByteAt         pgtype.Timestamptz `json:"first_byte_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	InputTokens         *int64             `json:"input_tokens"`
	OutputTokens        *int64             `json:"output_tokens"`
	UsageSource         UsageSource        `json:"usage_source"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ResponseRecord struct {
	ID                   uuid.UUID          `json:"id"`
	RequestID            *uuid.UUID         `json:"request_id"`
	GatewayKeyID         uuid.UUID          `json:"gateway_key_id"`
	PreviousResponseID   *uuid.UUID         `json:"previous_response_id"`
	IdempotencyKey       *string            `json:"idempotency_key"`
	RequestDigest        []byte             `json:"request_digest"`
	Status               ResponseStatus     `json:"status"`
	Background           bool               `json:"background"`
	EncryptedInput       []byte             `json:"encrypted_input"`
	EncryptedRequest     []byte             `json:"encrypted_request"`
	EncryptedOutput      []byte             `json:"encrypted_output"`
	EncryptedError       []byte             `json:"encrypted_error"`
	ExecutionID          *uuid.UUID         `json:"execution_id"`
	ExecutionGeneration  int64              `json:"execution_generation"`
	ExecutionClaimedAt   pgtype.Timestamptz `json:"execution_claimed_at"`
	ExecutionHeartbeatAt pgtype.Timestamptz `json:"execution_heartbeat_at"`
	CancelRequestedAt    pgtype.Timestamptz `json:"cancel_requested_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TokenDigest []byte             `json:"token_digest"`
	CsrfDigest  []byte             `json:"csrf_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SiteProfile struct {
	Singleton   bool               `json:"singleton"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Contact     string             `json:"contact"`
	Version     int64              `json:"version"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SystemState struct {
	Singleton      bool               `json:"singleton"`
	BootstrappedAt pgtype.Timestamptz `json:"bootstrapped_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Status       UserStatus         `json:"status"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
