// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAdministratorResourceSummary = `-- name: GetAdministratorResourceSummary :one
SELECT
  (SELECT count(*) FROM providers) AS provider_count,
  (SELECT count(*) FROM providers WHERE enabled) AS enabled_provider_count,
  (SELECT count(*) FROM models) AS model_count,
  (SELECT count(*) FROM provider_credentials) AS credential_count,
  (SELECT count(*) FROM provider_credentials WHERE status = 'active') AS active_credential_count,
  (SELECT count(*) FROM provider_credentials WHERE status = 'cooling') AS cooling_credential_count,
  (SELECT count(*) FROM users WHERE role = 'member' AND status = 'active') AS active_member_count,
  (SELECT count(*) FROM users WHERE role = 'member' AND status = 'pending') AS pending_member_count,
  (SELECT count(*) FROM gateway_keys key WHERE key.revoked_at IS NULL AND (key.expires_at IS NULL OR key.expires_at > $1)) AS active_gateway_key_count,
  (SELECT count(*) FROM entitlements entitlement WHERE entitlement.starts_at <= $1 AND entitlement.expires_at > $1) AS active_entitlement_count,
  EXISTS (SELECT 1 FROM active_config WHERE singleton = true) AS has_active_configuration,
  EXISTS (SELECT 1 FROM model_price_versions WHERE effective_at <= $1) AS has_model_price
`

type GetAdministratorResourceSummaryRow struct {
	ProviderCount          int64 `json:"provider_count"`
	EnabledProviderCount   int64 `json:"enabled_provider_count"`
	ModelCount             int64 `json:"model_count"`
	CredentialCount        int64 `json:"credential_count"`
	ActiveCredentialCount  int64 `json:"active_credential_count"`
	CoolingCredentialCount int64 `json:"cooling_credential_count"`
	ActiveMemberCount      int64 `json:"active_member_count"`
	PendingMemberCount     int64 `json:"pending_member_count"`
	ActiveGatewayKeyCount  int64 `json:"active_gateway_key_count"`
	ActiveEntitlementCount int64 `json:"active_entitlement_count"`
	HasActiveConfiguration bool  `json:"has_active_configuration"`
	HasModelPrice          bool  `json:"has_model_price"`
}

func (q *Queries) GetAdministratorResourceSummary(ctx context.Context, observedAt pgtype.Timestamptz) (GetAdministratorResourceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAdministratorResourceSummary, observedAt)
	var i GetAdministratorResourceSummaryRow
	err := row.Scan(
		&i.ProviderCount,
		&i.EnabledProviderCount,
		&i.ModelCount,
		&i.CredentialCount,
		&i.ActiveCredentialCount,
		&i.CoolingCredentialCount,
		&i.ActiveMemberCount,
		&i.PendingMemberCount,
		&i.ActiveGatewayKeyCount,
		&i.ActiveEntitlementCount,
		&i.HasActiveConfiguration,
		&i.HasModelPrice,
	)
	return i, err
}

const getAttemptLatencySummary = `-- name: GetAttemptLatencySummary :one
SELECT
  COALESCE((percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (attempt.first_byte_at - attempt.sent_at)) * 1000)
    FILTER (WHERE attempt.sent_at IS NOT NULL AND attempt.first_byte_at IS NOT NULL))::bigint, 0)::bigint AS first_byte_p95_ms,
  COALESCE((percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (attempt.completed_at - attempt.sent_at)) * 1000)
    FILTER (WHERE attempt.sent_at IS NOT NULL AND attempt.completed_at IS NOT NULL))::bigint, 0)::bigint AS total_p95_ms
FROM request_attempts attempt
JOIN requests request ON request.id = attempt.request_id
WHERE attempt.created_at >= $1
  AND attempt.created_at < $2
  AND ($3::uuid IS NULL OR request.user_id = $3)
`

type GetAttemptLatencySummaryParams struct {
	Since  pgtype.Timestamptz `json:"since"`
	Until  pgtype.Timestamptz `json:"until"`
	UserID *uuid.UUID         `json:"user_id"`
}

type GetAttemptLatencySummaryRow struct {
	FirstByteP95Ms int64 `json:"first_byte_p95_ms"`
	TotalP95Ms     int64 `json:"total_p95_ms"`
}

func (q *Queries) GetAttemptLatencySummary(ctx context.Context, arg GetAttemptLatencySummaryParams) (GetAttemptLatencySummaryRow, error) {
	row := q.db.QueryRow(ctx, getAttemptLatencySummary, arg.Since, arg.Until, arg.UserID)
	var i GetAttemptLatencySummaryRow
	err := row.Scan(&i.FirstByteP95Ms, &i.TotalP95Ms)
	return i, err
}

const getMemberAccessSummary = `-- name: GetMemberAccessSummary :one
SELECT
  (SELECT count(*) FROM gateway_keys key WHERE key.user_id = $1 AND key.revoked_at IS NULL AND (key.expires_at IS NULL OR key.expires_at > $2)) AS active_gateway_key_count,
  (SELECT count(*) FROM entitlements entitlement WHERE entitlement.user_id = $1 AND entitlement.starts_at <= $2 AND entitlement.expires_at > $2) AS active_entitlement_count,
  COALESCE((
    SELECT sum(balance.tokens)
    FROM entitlements entitlement
    CROSS JOIN LATERAL (
      SELECT COALESCE(sum(event.token_delta), 0)::bigint AS tokens
      FROM ledger_events event
      WHERE event.entitlement_id = entitlement.id
    ) balance
    WHERE entitlement.user_id = $1
      AND entitlement.starts_at <= $2
      AND entitlement.expires_at > $2
  ), 0)::bigint AS remaining_tokens,
  (SELECT min(entitlement.expires_at)::timestamptz FROM entitlements entitlement WHERE entitlement.user_id = $1 AND entitlement.starts_at <= $2 AND entitlement.expires_at > $2) AS nearest_entitlement_expiry
`

type GetMemberAccessSummaryParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

type GetMemberAccessSummaryRow struct {
	ActiveGatewayKeyCount    int64              `json:"active_gateway_key_count"`
	ActiveEntitlementCount   int64              `json:"active_entitlement_count"`
	RemainingTokens          int64              `json:"remaining_tokens"`
	NearestEntitlementExpiry pgtype.Timestamptz `json:"nearest_entitlement_expiry"`
}

func (q *Queries) GetMemberAccessSummary(ctx context.Context, arg GetMemberAccessSummaryParams) (GetMemberAccessSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMemberAccessSummary, arg.UserID, arg.ObservedAt)
	var i GetMemberAccessSummaryRow
	err := row.Scan(
		&i.ActiveGatewayKeyCount,
		&i.ActiveEntitlementCount,
		&i.RemainingTokens,
		&i.NearestEntitlementExpiry,
	)
	return i, err
}

const getRequestWindowSummary = `-- name: GetRequestWindowSummary :one
SELECT
  count(*) AS request_count,
  count(*) FILTER (WHERE status = 'completed') AS completed_count,
  count(*) FILTER (WHERE status IN ('failed', 'canceled')) AS failed_count,
  count(*) FILTER (WHERE status = 'uncertain') AS uncertain_count,
  COALESCE(sum(input_tokens) FILTER (WHERE input_tokens IS NOT NULL), 0)::bigint AS input_tokens,
  COALESCE(sum(output_tokens) FILTER (WHERE output_tokens IS NOT NULL), 0)::bigint AS output_tokens
FROM requests
WHERE accepted_at >= $1
  AND accepted_at < $2
  AND ($3::uuid IS NULL OR user_id = $3)
`

type GetRequestWindowSummaryParams struct {
	Since  pgtype.Timestamptz `json:"since"`
	Until  pgtype.Timestamptz `json:"until"`
	UserID *uuid.UUID         `json:"user_id"`
}

type GetRequestWindowSummaryRow struct {
	RequestCount   int64 `json:"request_count"`
	CompletedCount int64 `json:"completed_count"`
	FailedCount    int64 `json:"failed_count"`
	UncertainCount int64 `json:"uncertain_count"`
	InputTokens    int64 `json:"input_tokens"`
	OutputTokens   int64 `json:"output_tokens"`
}

func (q *Queries) GetRequestWindowSummary(ctx context.Context, arg GetRequestWindowSummaryParams) (GetRequestWindowSummaryRow, error) {
	row := q.db.QueryRow(ctx, getRequestWindowSummary, arg.Since, arg.Until, arg.UserID)
	var i GetRequestWindowSummaryRow
	err := row.Scan(
		&i.RequestCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.UncertainCount,
		&i.InputTokens,
		&i.OutputTokens,
	)
	return i, err
}

const listRequestErrors = `-- name: ListRequestErrors :many
SELECT COALESCE(error_kind, 'unknown') AS error_kind, count(*) AS request_count
FROM requests
WHERE accepted_at >= $1
  AND accepted_at < $2
  AND status IN ('failed', 'canceled', 'uncertain')
  AND ($3::uuid IS NULL OR user_id = $3)
GROUP BY COALESCE(error_kind, 'unknown')
ORDER BY request_count DESC, error_kind
LIMIT 8
`

type ListRequestErrorsParams struct {
	Since  pgtype.Timestamptz `json:"since"`
	Until  pgtype.Timestamptz `json:"until"`
	UserID *uuid.UUID         `json:"user_id"`
}

type ListRequestErrorsRow struct {
	ErrorKind    string `json:"error_kind"`
	RequestCount int64  `json:"request_count"`
}

func (q *Queries) ListRequestErrors(ctx context.Context, arg ListRequestErrorsParams) ([]ListRequestErrorsRow, error) {
	rows, err := q.db.Query(ctx, listRequestErrors, arg.Since, arg.Until, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestErrorsRow{}
	for rows.Next() {
		var i ListRequestErrorsRow
		if err := rows.Scan(&i.ErrorKind, &i.RequestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestTrend = `-- name: ListRequestTrend :many
WITH buckets AS (
  SELECT generate_series($1::timestamptz, $2::timestamptz - interval '1 hour', interval '1 hour') AS bucket
), facts AS (
  SELECT date_trunc('hour', accepted_at) AS bucket,
         count(*) AS request_count,
         COALESCE(sum(input_tokens) FILTER (WHERE input_tokens IS NOT NULL), 0)::bigint AS input_tokens,
         COALESCE(sum(output_tokens) FILTER (WHERE output_tokens IS NOT NULL), 0)::bigint AS output_tokens
  FROM requests
  WHERE accepted_at >= $1
    AND accepted_at < $2
    AND ($3::uuid IS NULL OR user_id = $3)
  GROUP BY date_trunc('hour', accepted_at)
)
SELECT buckets.bucket::timestamptz AS bucket,
       COALESCE(facts.request_count, 0)::bigint AS request_count,
       COALESCE(facts.input_tokens, 0)::bigint AS input_tokens,
       COALESCE(facts.output_tokens, 0)::bigint AS output_tokens
FROM buckets
LEFT JOIN facts USING (bucket)
ORDER BY buckets.bucket
`

type ListRequestTrendParams struct {
	Since  pgtype.Timestamptz `json:"since"`
	Until  pgtype.Timestamptz `json:"until"`
	UserID *uuid.UUID         `json:"user_id"`
}

type ListRequestTrendRow struct {
	Bucket       pgtype.Timestamptz `json:"bucket"`
	RequestCount int64              `json:"request_count"`
	InputTokens  int64              `json:"input_tokens"`
	OutputTokens int64              `json:"output_tokens"`
}

func (q *Queries) ListRequestTrend(ctx context.Context, arg ListRequestTrendParams) ([]ListRequestTrendRow, error) {
	rows, err := q.db.Query(ctx, listRequestTrend, arg.Since, arg.Until, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestTrendRow{}
	for rows.Next() {
		var i ListRequestTrendRow
		if err := rows.Scan(
			&i.Bucket,
			&i.RequestCount,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
