// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindCredentialModel = `-- name: BindCredentialModel :exec
INSERT INTO credential_models (credential_id, model_id, priority, weight)
VALUES ($1, $2, $3, $4)
ON CONFLICT (credential_id, model_id) DO UPDATE SET priority = excluded.priority, weight = excluded.weight
`

type BindCredentialModelParams struct {
	CredentialID uuid.UUID `json:"credential_id"`
	ModelID      uuid.UUID `json:"model_id"`
	Priority     int32     `json:"priority"`
	Weight       int32     `json:"weight"`
}

func (q *Queries) BindCredentialModel(ctx context.Context, arg BindCredentialModelParams) error {
	_, err := q.db.Exec(ctx, bindCredentialModel,
		arg.CredentialID,
		arg.ModelID,
		arg.Priority,
		arg.Weight,
	)
	return err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO provider_credentials (id, provider_id, name, encrypted_secret, resource_domain, rpm_limit, tpm_limit, concurrency_limit, fixed_proxy_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, provider_id, name, encrypted_secret, resource_domain, status, rpm_limit, tpm_limit, concurrency_limit, fixed_proxy_url, cooldown_until, consecutive_failures, last_success_at, last_error_kind, created_at, updated_at
`

type CreateCredentialParams struct {
	ID               uuid.UUID      `json:"id"`
	ProviderID       uuid.UUID      `json:"provider_id"`
	Name             string         `json:"name"`
	EncryptedSecret  []byte         `json:"encrypted_secret"`
	ResourceDomain   ResourceDomain `json:"resource_domain"`
	RpmLimit         *int32         `json:"rpm_limit"`
	TpmLimit         *int64         `json:"tpm_limit"`
	ConcurrencyLimit *int32         `json:"concurrency_limit"`
	FixedProxyUrl    *string        `json:"fixed_proxy_url"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.ProviderID,
		arg.Name,
		arg.EncryptedSecret,
		arg.ResourceDomain,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.ConcurrencyLimit,
		arg.FixedProxyUrl,
	)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.EncryptedSecret,
		&i.ResourceDomain,
		&i.Status,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.ConcurrencyLimit,
		&i.FixedProxyUrl,
		&i.CooldownUntil,
		&i.ConsecutiveFailures,
		&i.LastSuccessAt,
		&i.LastErrorKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO models (provider_id, public_name, upstream_name, display_name, resource_domain, capabilities, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, public_name, upstream_name, display_name, resource_domain, capabilities, enabled, created_at, updated_at
`

type CreateModelParams struct {
	ProviderID     uuid.UUID      `json:"provider_id"`
	PublicName     string         `json:"public_name"`
	UpstreamName   string         `json:"upstream_name"`
	DisplayName    string         `json:"display_name"`
	ResourceDomain ResourceDomain `json:"resource_domain"`
	Capabilities   []byte         `json:"capabilities"`
	Enabled        bool           `json:"enabled"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.ProviderID,
		arg.PublicName,
		arg.UpstreamName,
		arg.DisplayName,
		arg.ResourceDomain,
		arg.Capabilities,
		arg.Enabled,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.PublicName,
		&i.UpstreamName,
		&i.DisplayName,
		&i.ResourceDomain,
		&i.Capabilities,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (slug, name, kind, base_url, enabled, source_url, verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, name, kind, base_url, enabled, source_url, verified_at, created_at, updated_at
`

type CreateProviderParams struct {
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	BaseUrl    string             `json:"base_url"`
	Enabled    bool               `json:"enabled"`
	SourceUrl  *string            `json:"source_url"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.Enabled,
		arg.SourceUrl,
		arg.VerifiedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.Enabled,
		&i.SourceUrl,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialSecret = `-- name: GetCredentialSecret :one
SELECT id, provider_id, name, encrypted_secret, resource_domain, status, rpm_limit, tpm_limit, concurrency_limit, fixed_proxy_url, cooldown_until, consecutive_failures, last_success_at, last_error_kind, created_at, updated_at FROM provider_credentials WHERE id = $1
`

func (q *Queries) GetCredentialSecret(ctx context.Context, id uuid.UUID) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialSecret, id)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.EncryptedSecret,
		&i.ResourceDomain,
		&i.Status,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.ConcurrencyLimit,
		&i.FixedProxyUrl,
		&i.CooldownUntil,
		&i.ConsecutiveFailures,
		&i.LastSuccessAt,
		&i.LastErrorKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelByPublicName = `-- name: GetModelByPublicName :one
SELECT m.id, m.provider_id, m.public_name, m.upstream_name, m.display_name, m.resource_domain, m.capabilities, m.enabled, m.created_at, m.updated_at, p.slug AS provider_slug, p.kind AS provider_kind, p.base_url AS provider_base_url, p.enabled AS provider_enabled
FROM models m JOIN providers p ON p.id = m.provider_id WHERE m.public_name = $1
`

type GetModelByPublicNameRow struct {
	ID              uuid.UUID          `json:"id"`
	ProviderID      uuid.UUID          `json:"provider_id"`
	PublicName      string             `json:"public_name"`
	UpstreamName    string             `json:"upstream_name"`
	DisplayName     string             `json:"display_name"`
	ResourceDomain  ResourceDomain     `json:"resource_domain"`
	Capabilities    []byte             `json:"capabilities"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProviderSlug    string             `json:"provider_slug"`
	ProviderKind    string             `json:"provider_kind"`
	ProviderBaseUrl string             `json:"provider_base_url"`
	ProviderEnabled bool               `json:"provider_enabled"`
}

func (q *Queries) GetModelByPublicName(ctx context.Context, publicName string) (GetModelByPublicNameRow, error) {
	row := q.db.QueryRow(ctx, getModelByPublicName, publicName)
	var i GetModelByPublicNameRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.PublicName,
		&i.UpstreamName,
		&i.DisplayName,
		&i.ResourceDomain,
		&i.Capabilities,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderSlug,
		&i.ProviderKind,
		&i.ProviderBaseUrl,
		&i.ProviderEnabled,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, slug, name, kind, base_url, enabled, source_url, verified_at, created_at, updated_at FROM providers WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.Enabled,
		&i.SourceUrl,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthorizedModels = `-- name: ListAuthorizedModels :many
SELECT m.id, m.provider_id, m.public_name, m.upstream_name, m.display_name, m.resource_domain, m.capabilities, m.enabled, m.created_at, m.updated_at, p.slug AS provider_slug, p.name AS provider_name
FROM models m
JOIN providers p ON p.id = m.provider_id
JOIN model_authorizations a ON a.model_id = m.id
WHERE a.user_id = $1 AND m.enabled AND p.enabled
ORDER BY m.public_name, m.id
`

type ListAuthorizedModelsRow struct {
	ID             uuid.UUID          `json:"id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	PublicName     string             `json:"public_name"`
	UpstreamName   string             `json:"upstream_name"`
	DisplayName    string             `json:"display_name"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
	Capabilities   []byte             `json:"capabilities"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProviderSlug   string             `json:"provider_slug"`
	ProviderName   string             `json:"provider_name"`
}

func (q *Queries) ListAuthorizedModels(ctx context.Context, userID uuid.UUID) ([]ListAuthorizedModelsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedModels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizedModelsRow{}
	for rows.Next() {
		var i ListAuthorizedModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.PublicName,
			&i.UpstreamName,
			&i.DisplayName,
			&i.ResourceDomain,
			&i.Capabilities,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderSlug,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, provider_id, name, resource_domain, status, rpm_limit, tpm_limit, concurrency_limit, fixed_proxy_url, cooldown_until, consecutive_failures, last_success_at, last_error_kind, created_at, updated_at
FROM provider_credentials ORDER BY name, id
`

type ListCredentialsRow struct {
	ID                  uuid.UUID          `json:"id"`
	ProviderID          uuid.UUID          `json:"provider_id"`
	Name                string             `json:"name"`
	ResourceDomain      ResourceDomain     `json:"resource_domain"`
	Status              CredentialStatus   `json:"status"`
	RpmLimit            *int32             `json:"rpm_limit"`
	TpmLimit            *int64             `json:"tpm_limit"`
	ConcurrencyLimit    *int32             `json:"concurrency_limit"`
	FixedProxyUrl       *string            `json:"fixed_proxy_url"`
	CooldownUntil       pgtype.Timestamptz `json:"cooldown_until"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastErrorKind       *string            `json:"last_error_kind"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCredentials(ctx context.Context) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.ResourceDomain,
			&i.Status,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.ConcurrencyLimit,
			&i.FixedProxyUrl,
			&i.CooldownUntil,
			&i.ConsecutiveFailures,
			&i.LastSuccessAt,
			&i.LastErrorKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleCredentials = `-- name: ListEligibleCredentials :many
SELECT c.id, c.provider_id, c.name, c.encrypted_secret, c.resource_domain, c.status, c.rpm_limit, c.tpm_limit, c.concurrency_limit, c.fixed_proxy_url, c.cooldown_until, c.consecutive_failures, c.last_success_at, c.last_error_kind, c.created_at, c.updated_at, cm.priority, cm.weight
FROM provider_credentials c
JOIN credential_models cm ON cm.credential_id = c.id
WHERE cm.model_id = $1
  AND c.resource_domain = $2
  AND c.status <> 'disabled'
  AND (c.cooldown_until IS NULL OR c.cooldown_until <= now())
ORDER BY cm.priority, c.id
`

type ListEligibleCredentialsParams struct {
	ModelID        uuid.UUID      `json:"model_id"`
	ResourceDomain ResourceDomain `json:"resource_domain"`
}

type ListEligibleCredentialsRow struct {
	ID                  uuid.UUID          `json:"id"`
	ProviderID          uuid.UUID          `json:"provider_id"`
	Name                string             `json:"name"`
	EncryptedSecret     []byte             `json:"encrypted_secret"`
	ResourceDomain      ResourceDomain     `json:"resource_domain"`
	Status              CredentialStatus   `json:"status"`
	RpmLimit            *int32             `json:"rpm_limit"`
	TpmLimit            *int64             `json:"tpm_limit"`
	ConcurrencyLimit    *int32             `json:"concurrency_limit"`
	FixedProxyUrl       *string            `json:"fixed_proxy_url"`
	CooldownUntil       pgtype.Timestamptz `json:"cooldown_until"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastErrorKind       *string            `json:"last_error_kind"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Priority            int32              `json:"priority"`
	Weight              int32              `json:"weight"`
}

func (q *Queries) ListEligibleCredentials(ctx context.Context, arg ListEligibleCredentialsParams) ([]ListEligibleCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleCredentials, arg.ModelID, arg.ResourceDomain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligibleCredentialsRow{}
	for rows.Next() {
		var i ListEligibleCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.EncryptedSecret,
			&i.ResourceDomain,
			&i.Status,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.ConcurrencyLimit,
			&i.FixedProxyUrl,
			&i.CooldownUntil,
			&i.ConsecutiveFailures,
			&i.LastSuccessAt,
			&i.LastErrorKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT m.id, m.provider_id, m.public_name, m.upstream_name, m.display_name, m.resource_domain, m.capabilities, m.enabled, m.created_at, m.updated_at, p.slug AS provider_slug, p.name AS provider_name
FROM models m JOIN providers p ON p.id = m.provider_id ORDER BY m.public_name, m.id
`

type ListModelsRow struct {
	ID             uuid.UUID          `json:"id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	PublicName     string             `json:"public_name"`
	UpstreamName   string             `json:"upstream_name"`
	DisplayName    string             `json:"display_name"`
	ResourceDomain ResourceDomain     `json:"resource_domain"`
	Capabilities   []byte             `json:"capabilities"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProviderSlug   string             `json:"provider_slug"`
	ProviderName   string             `json:"provider_name"`
}

func (q *Queries) ListModels(ctx context.Context) ([]ListModelsRow, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelsRow{}
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.PublicName,
			&i.UpstreamName,
			&i.DisplayName,
			&i.ResourceDomain,
			&i.Capabilities,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderSlug,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, slug, name, kind, base_url, enabled, source_url, verified_at, created_at, updated_at FROM providers ORDER BY name, id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.Enabled,
			&i.SourceUrl,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialState = `-- name: UpdateCredentialState :one
UPDATE provider_credentials
SET status = $1, cooldown_until = $2, consecutive_failures = $3, last_success_at = $4, last_error_kind = $5, updated_at = now()
WHERE id = $6 RETURNING id, provider_id, name, encrypted_secret, resource_domain, status, rpm_limit, tpm_limit, concurrency_limit, fixed_proxy_url, cooldown_until, consecutive_failures, last_success_at, last_error_kind, created_at, updated_at
`

type UpdateCredentialStateParams struct {
	Status              CredentialStatus   `json:"status"`
	CooldownUntil       pgtype.Timestamptz `json:"cooldown_until"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastErrorKind       *string            `json:"last_error_kind"`
	ID                  uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateCredentialState(ctx context.Context, arg UpdateCredentialStateParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, updateCredentialState,
		arg.Status,
		arg.CooldownUntil,
		arg.ConsecutiveFailures,
		arg.LastSuccessAt,
		arg.LastErrorKind,
		arg.ID,
	)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.EncryptedSecret,
		&i.ResourceDomain,
		&i.Status,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.ConcurrencyLimit,
		&i.FixedProxyUrl,
		&i.CooldownUntil,
		&i.ConsecutiveFailures,
		&i.LastSuccessAt,
		&i.LastErrorKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models SET public_name = $1, upstream_name = $2, display_name = $3, resource_domain = $4, capabilities = $5, enabled = $6, updated_at = now()
WHERE id = $7 RETURNING id, provider_id, public_name, upstream_name, display_name, resource_domain, capabilities, enabled, created_at, updated_at
`

type UpdateModelParams struct {
	PublicName     string         `json:"public_name"`
	UpstreamName   string         `json:"upstream_name"`
	DisplayName    string         `json:"display_name"`
	ResourceDomain ResourceDomain `json:"resource_domain"`
	Capabilities   []byte         `json:"capabilities"`
	Enabled        bool           `json:"enabled"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.PublicName,
		arg.UpstreamName,
		arg.DisplayName,
		arg.ResourceDomain,
		arg.Capabilities,
		arg.Enabled,
		arg.ID,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.PublicName,
		&i.UpstreamName,
		&i.DisplayName,
		&i.ResourceDomain,
		&i.Capabilities,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET name = $1, kind = $2, base_url = $3, enabled = $4, source_url = $5, verified_at = $6, updated_at = now()
WHERE id = $7 RETURNING id, slug, name, kind, base_url, enabled, source_url, verified_at, created_at, updated_at
`

type UpdateProviderParams struct {
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	BaseUrl    string             `json:"base_url"`
	Enabled    bool               `json:"enabled"`
	SourceUrl  *string            `json:"source_url"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.Enabled,
		arg.SourceUrl,
		arg.VerifiedAt,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.Enabled,
		&i.SourceUrl,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
