// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AuthorizeUserModel(ctx context.Context, arg AuthorizeUserModelParams) error
	BindCredentialModel(ctx context.Context, arg BindCredentialModelParams) error
	ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (int64, error)
	CompleteLedgerReservation(ctx context.Context, arg CompleteLedgerReservationParams) (LedgerReservation, error)
	CompleteRequest(ctx context.Context, arg CompleteRequestParams) (Request, error)
	CountUsers(ctx context.Context, status *UserStatus) (int64, error)
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (RequestAttempt, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateConfigOutbox(ctx context.Context, arg CreateConfigOutboxParams) error
	CreateConfigRevision(ctx context.Context, arg CreateConfigRevisionParams) (ConfigRevision, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (ProviderCredential, error)
	CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (Entitlement, error)
	CreateGatewayKey(ctx context.Context, arg CreateGatewayKeyParams) (GatewayKey, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateLedgerEvent(ctx context.Context, arg CreateLedgerEventParams) (LedgerEvent, error)
	CreateLedgerReservation(ctx context.Context, arg CreateLedgerReservationParams) (LedgerReservation, error)
	CreateModel(ctx context.Context, arg CreateModelParams) (Model, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateResponseRecord(ctx context.Context, arg CreateResponseRecordParams) (ResponseRecord, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredContent(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	EntitlementBalance(ctx context.Context, entitlementID uuid.UUID) (int64, error)
	FailRequestWithUsage(ctx context.Context, arg FailRequestWithUsageParams) (Request, error)
	GetActiveConfig(ctx context.Context) (GetActiveConfigRow, error)
	GetAuthorizedModelDomain(ctx context.Context, arg GetAuthorizedModelDomainParams) (ResourceDomain, error)
	GetConfigRevision(ctx context.Context, id uuid.UUID) (ConfigRevision, error)
	GetContentRecord(ctx context.Context, requestID uuid.UUID) (ContentRecord, error)
	GetCredentialSecret(ctx context.Context, id uuid.UUID) (ProviderCredential, error)
	GetEntitlementByGrantIdempotency(ctx context.Context, arg GetEntitlementByGrantIdempotencyParams) (GetEntitlementByGrantIdempotencyRow, error)
	GetEntitlementForUpdate(ctx context.Context, id uuid.UUID) (Entitlement, error)
	GetGatewayKeyByDigest(ctx context.Context, secretDigest []byte) (GetGatewayKeyByDigestRow, error)
	GetInvitationByDigestForUpdate(ctx context.Context, codeDigest []byte) (Invitation, error)
	GetLedgerReservationByRequest(ctx context.Context, requestID uuid.UUID) (LedgerReservation, error)
	GetLedgerReservationByRequestForUpdate(ctx context.Context, requestID uuid.UUID) (LedgerReservation, error)
	GetLedgerReservationForUpdate(ctx context.Context, id uuid.UUID) (LedgerReservation, error)
	GetModelByPublicName(ctx context.Context, publicName string) (GetModelByPublicNameRow, error)
	GetModelDomain(ctx context.Context, modelID uuid.UUID) (ResourceDomain, error)
	GetProvider(ctx context.Context, id uuid.UUID) (Provider, error)
	GetProviderForUpdate(ctx context.Context, id uuid.UUID) (Provider, error)
	GetRequest(ctx context.Context, id uuid.UUID) (Request, error)
	GetRequestByIdempotencyKey(ctx context.Context, arg GetRequestByIdempotencyKeyParams) (Request, error)
	GetRequestForUpdate(ctx context.Context, id uuid.UUID) (Request, error)
	GetResponseRecord(ctx context.Context, id uuid.UUID) (ResponseRecord, error)
	GetSessionByDigest(ctx context.Context, tokenDigest []byte) (GetSessionByDigestRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InitializeActiveConfig(ctx context.Context, revisionID uuid.UUID) (int64, error)
	IsBootstrapped(ctx context.Context) (bool, error)
	IsGatewayKeyOwnedByUser(ctx context.Context, arg IsGatewayKeyOwnedByUserParams) (bool, error)
	IsUserAuthorizedForModel(ctx context.Context, arg IsUserAuthorizedForModelParams) (bool, error)
	ListActiveEntitlements(ctx context.Context, userID uuid.UUID) ([]Entitlement, error)
	ListApplicableEntitlementsForUpdate(ctx context.Context, arg ListApplicableEntitlementsForUpdateParams) ([]Entitlement, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuthorizedModels(ctx context.Context, userID uuid.UUID) ([]ListAuthorizedModelsRow, error)
	ListConfigRevisions(ctx context.Context, arg ListConfigRevisionsParams) ([]ConfigRevision, error)
	ListCredentials(ctx context.Context) ([]ListCredentialsRow, error)
	ListEligibleCredentials(ctx context.Context, arg ListEligibleCredentialsParams) ([]ListEligibleCredentialsRow, error)
	ListEntitlementsWithBalance(ctx context.Context, arg ListEntitlementsWithBalanceParams) ([]ListEntitlementsWithBalanceRow, error)
	ListGatewayKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListGatewayKeysByUserRow, error)
	ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error)
	ListLedgerEvents(ctx context.Context, arg ListLedgerEventsParams) ([]LedgerEvent, error)
	ListLedgerEventsByEntitlement(ctx context.Context, entitlementID uuid.UUID) ([]LedgerEvent, error)
	ListModels(ctx context.Context) ([]ListModelsRow, error)
	ListPendingConfigOutbox(ctx context.Context, batchSize int32) ([]ConfigOutbox, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListRequestAttempts(ctx context.Context, requestID uuid.UUID) ([]RequestAttempt, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]Request, error)
	ListUserModelAuthorizations(ctx context.Context, userID uuid.UUID) ([]ListUserModelAuthorizationsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockActiveConfig(ctx context.Context) (LockActiveConfigRow, error)
	MarkBootstrapped(ctx context.Context) (int64, error)
	MarkConfigOutboxDelivered(ctx context.Context, id int64) error
	MarkConfigOutboxFailed(ctx context.Context, arg MarkConfigOutboxFailedParams) error
	MarkConfigPublished(ctx context.Context, arg MarkConfigPublishedParams) error
	PublishConfigRevision(ctx context.Context, arg PublishConfigRevisionParams) (int64, error)
	RequestResponseCancellation(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeGatewayKey(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeInvitation(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeOwnedGatewayKey(ctx context.Context, arg RevokeOwnedGatewayKeyParams) (int64, error)
	RevokeSession(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeUserModel(ctx context.Context, arg RevokeUserModelParams) (int64, error)
	RevokeUserSessions(ctx context.Context, userID uuid.UUID) error
	SetProviderEnabled(ctx context.Context, arg SetProviderEnabledParams) (Provider, error)
	TouchGatewayKey(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) (RequestAttempt, error)
	UpdateCredentialState(ctx context.Context, arg UpdateCredentialStateParams) (ProviderCredential, error)
	UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error)
	UpdateResponseRecord(ctx context.Context, arg UpdateResponseRecordParams) (ResponseRecord, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertContentRecord(ctx context.Context, arg UpsertContentRecordParams) error
}

var _ Querier = (*Queries)(nil)
