// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSiteProfile = `-- name: GetSiteProfile :one
SELECT singleton, name, description, contact, version, updated_by, updated_at FROM site_profile WHERE singleton = true
`

func (q *Queries) GetSiteProfile(ctx context.Context) (SiteProfile, error) {
	row := q.db.QueryRow(ctx, getSiteProfile)
	var i SiteProfile
	err := row.Scan(
		&i.Singleton,
		&i.Name,
		&i.Description,
		&i.Contact,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteProfile = `-- name: UpdateSiteProfile :one
UPDATE site_profile
SET name = $1,
    description = $2,
    contact = $3,
    version = version + 1,
    updated_by = $4,
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE singleton = true AND version = $5
RETURNING singleton, name, description, contact, version, updated_by, updated_at
`

type UpdateSiteProfileParams struct {
	Name            string     `json:"name"`
	Description     string     `json:"description"`
	Contact         string     `json:"contact"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
	ExpectedVersion int64      `json:"expected_version"`
}

func (q *Queries) UpdateSiteProfile(ctx context.Context, arg UpdateSiteProfileParams) (SiteProfile, error) {
	row := q.db.QueryRow(ctx, updateSiteProfile,
		arg.Name,
		arg.Description,
		arg.Contact,
		arg.UpdatedBy,
		arg.ExpectedVersion,
	)
	var i SiteProfile
	err := row.Scan(
		&i.Singleton,
		&i.Name,
		&i.Description,
		&i.Contact,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
