// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimServicePlanMutation = `-- name: ClaimServicePlanMutation :one
INSERT INTO service_plan_mutations (actor_user_id, action, idempotency_key, request_fingerprint, request_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (actor_user_id, action, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, action, idempotency_key, request_fingerprint, request_id, service_plan_id, result, created_at
`

type ClaimServicePlanMutationParams struct {
	ActorUserID        uuid.UUID `json:"actor_user_id"`
	Action             string    `json:"action"`
	IdempotencyKey     uuid.UUID `json:"idempotency_key"`
	RequestFingerprint []byte    `json:"request_fingerprint"`
	RequestID          string    `json:"request_id"`
}

func (q *Queries) ClaimServicePlanMutation(ctx context.Context, arg ClaimServicePlanMutationParams) (ServicePlanMutation, error) {
	row := q.db.QueryRow(ctx, claimServicePlanMutation,
		arg.ActorUserID,
		arg.Action,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.RequestID,
	)
	var i ServicePlanMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.ServicePlanID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const claimSubscriptionMutation = `-- name: ClaimSubscriptionMutation :one
INSERT INTO subscription_mutations (actor_user_id, action, idempotency_key, request_fingerprint, request_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (actor_user_id, action, idempotency_key) DO NOTHING
RETURNING id, actor_user_id, action, idempotency_key, request_fingerprint, request_id, subscription_id, result, created_at
`

type ClaimSubscriptionMutationParams struct {
	ActorUserID        uuid.UUID `json:"actor_user_id"`
	Action             string    `json:"action"`
	IdempotencyKey     uuid.UUID `json:"idempotency_key"`
	RequestFingerprint []byte    `json:"request_fingerprint"`
	RequestID          string    `json:"request_id"`
}

func (q *Queries) ClaimSubscriptionMutation(ctx context.Context, arg ClaimSubscriptionMutationParams) (SubscriptionMutation, error) {
	row := q.db.QueryRow(ctx, claimSubscriptionMutation,
		arg.ActorUserID,
		arg.Action,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.RequestID,
	)
	var i SubscriptionMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.SubscriptionID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeServicePlanMutation = `-- name: CompleteServicePlanMutation :one
UPDATE service_plan_mutations SET service_plan_id = $1, result = $2
WHERE id = $3 RETURNING id, actor_user_id, action, idempotency_key, request_fingerprint, request_id, service_plan_id, result, created_at
`

type CompleteServicePlanMutationParams struct {
	ServicePlanID *uuid.UUID `json:"service_plan_id"`
	Result        []byte     `json:"result"`
	ID            uuid.UUID  `json:"id"`
}

func (q *Queries) CompleteServicePlanMutation(ctx context.Context, arg CompleteServicePlanMutationParams) (ServicePlanMutation, error) {
	row := q.db.QueryRow(ctx, completeServicePlanMutation, arg.ServicePlanID, arg.Result, arg.ID)
	var i ServicePlanMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.ServicePlanID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const completeSubscriptionMutation = `-- name: CompleteSubscriptionMutation :one
UPDATE subscription_mutations SET subscription_id = $1, result = $2
WHERE id = $3 RETURNING id, actor_user_id, action, idempotency_key, request_fingerprint, request_id, subscription_id, result, created_at
`

type CompleteSubscriptionMutationParams struct {
	SubscriptionID *uuid.UUID `json:"subscription_id"`
	Result         []byte     `json:"result"`
	ID             uuid.UUID  `json:"id"`
}

func (q *Queries) CompleteSubscriptionMutation(ctx context.Context, arg CompleteSubscriptionMutationParams) (SubscriptionMutation, error) {
	row := q.db.QueryRow(ctx, completeSubscriptionMutation, arg.SubscriptionID, arg.Result, arg.ID)
	var i SubscriptionMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.SubscriptionID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const countSubscriptions = `-- name: CountSubscriptions :one
SELECT count(*)
FROM subscriptions subscription
JOIN service_plan_versions version ON version.id = subscription.service_plan_version_id
JOIN service_plans plan ON plan.id = version.service_plan_id
JOIN users member ON member.id = subscription.user_id
WHERE ($1::uuid IS NULL OR subscription.user_id = $1)
  AND ($2::text = '' OR concat_ws(' ', member.email, member.display_name, plan.name) ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR
       CASE
         WHEN subscription.status IN ('suspended', 'canceled') THEN subscription.status::text
         WHEN subscription.expires_at <= now() THEN 'expired'
         WHEN subscription.starts_at > now() THEN 'scheduled'
         ELSE 'active'
       END = $3::text)
`

type CountSubscriptionsParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Search string     `json:"search"`
	Status string     `json:"status"`
}

func (q *Queries) CountSubscriptions(ctx context.Context, arg CountSubscriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptions, arg.UserID, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServicePlan = `-- name: CreateServicePlan :one
INSERT INTO service_plans (slug, name, description, kind, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, description, kind, status, current_version_id, created_by, created_at, updated_at
`

type CreateServicePlanParams struct {
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Kind        PlanKind  `json:"kind"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateServicePlan(ctx context.Context, arg CreateServicePlanParams) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, createServicePlan,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.CreatedBy,
	)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServicePlanVersion = `-- name: CreateServicePlanVersion :one
INSERT INTO service_plan_versions (
  service_plan_id, version, token_quota, validity_days, concurrency_limit, rpm_limit, tpm_limit, created_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
) RETURNING id, service_plan_id, version, token_quota, validity_days, concurrency_limit, rpm_limit, tpm_limit, created_by, created_at
`

type CreateServicePlanVersionParams struct {
	ServicePlanID    uuid.UUID `json:"service_plan_id"`
	Version          int32     `json:"version"`
	TokenQuota       int64     `json:"token_quota"`
	ValidityDays     int32     `json:"validity_days"`
	ConcurrencyLimit int32     `json:"concurrency_limit"`
	RpmLimit         *int32    `json:"rpm_limit"`
	TpmLimit         *int64    `json:"tpm_limit"`
	CreatedBy        uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateServicePlanVersion(ctx context.Context, arg CreateServicePlanVersionParams) (ServicePlanVersion, error) {
	row := q.db.QueryRow(ctx, createServicePlanVersion,
		arg.ServicePlanID,
		arg.Version,
		arg.TokenQuota,
		arg.ValidityDays,
		arg.ConcurrencyLimit,
		arg.RpmLimit,
		arg.TpmLimit,
		arg.CreatedBy,
	)
	var i ServicePlanVersion
	err := row.Scan(
		&i.ID,
		&i.ServicePlanID,
		&i.Version,
		&i.TokenQuota,
		&i.ValidityDays,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createServicePlanVersionRoute = `-- name: CreateServicePlanVersionRoute :exec
INSERT INTO service_plan_version_routes (service_plan_version_id, model_id, resource_pool_id)
VALUES ($1, $2, $3)
`

type CreateServicePlanVersionRouteParams struct {
	ServicePlanVersionID uuid.UUID `json:"service_plan_version_id"`
	ModelID              uuid.UUID `json:"model_id"`
	ResourcePoolID       uuid.UUID `json:"resource_pool_id"`
}

func (q *Queries) CreateServicePlanVersionRoute(ctx context.Context, arg CreateServicePlanVersionRouteParams) error {
	_, err := q.db.Exec(ctx, createServicePlanVersionRoute, arg.ServicePlanVersionID, arg.ModelID, arg.ResourcePoolID)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  user_id, service_plan_version_id, status, granted_tokens, starts_at, expires_at, notes, assigned_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
) RETURNING id, user_id, service_plan_version_id, status, granted_tokens, starts_at, expires_at, notes, assigned_by, suspended_at, canceled_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID               uuid.UUID          `json:"user_id"`
	ServicePlanVersionID uuid.UUID          `json:"service_plan_version_id"`
	Status               SubscriptionStatus `json:"status"`
	GrantedTokens        int64              `json:"granted_tokens"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Notes                string             `json:"notes"`
	AssignedBy           uuid.UUID          `json:"assigned_by"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.ServicePlanVersionID,
		arg.Status,
		arg.GrantedTokens,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.Notes,
		arg.AssignedBy,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServicePlanVersionID,
		&i.Status,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Notes,
		&i.AssignedBy,
		&i.SuspendedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicableSubscriptionRoutesForUpdate = `-- name: GetApplicableSubscriptionRoutesForUpdate :many
SELECT subscription.id, subscription.user_id, subscription.service_plan_version_id, subscription.status, subscription.granted_tokens, subscription.starts_at, subscription.expires_at, subscription.notes, subscription.assigned_by, subscription.suspended_at, subscription.canceled_at, subscription.created_at, subscription.updated_at, version.concurrency_limit, version.rpm_limit, version.tpm_limit,
       route.resource_pool_id
FROM subscriptions subscription
JOIN service_plan_versions version ON version.id = subscription.service_plan_version_id
JOIN service_plan_version_routes route ON route.service_plan_version_id = version.id
JOIN resource_pools pool ON pool.id = route.resource_pool_id
WHERE subscription.user_id = $1 AND route.model_id = $2
  AND subscription.status IN ('scheduled', 'active')
  AND subscription.starts_at <= now() AND subscription.expires_at > now()
  AND pool.status = 'active'
ORDER BY subscription.expires_at, subscription.created_at, subscription.id
FOR UPDATE OF subscription
`

type GetApplicableSubscriptionRoutesForUpdateParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ModelID uuid.UUID `json:"model_id"`
}

type GetApplicableSubscriptionRoutesForUpdateRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	ServicePlanVersionID uuid.UUID          `json:"service_plan_version_id"`
	Status               SubscriptionStatus `json:"status"`
	GrantedTokens        int64              `json:"granted_tokens"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Notes                string             `json:"notes"`
	AssignedBy           uuid.UUID          `json:"assigned_by"`
	SuspendedAt          pgtype.Timestamptz `json:"suspended_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ConcurrencyLimit     int32              `json:"concurrency_limit"`
	RpmLimit             *int32             `json:"rpm_limit"`
	TpmLimit             *int64             `json:"tpm_limit"`
	ResourcePoolID       uuid.UUID          `json:"resource_pool_id"`
}

func (q *Queries) GetApplicableSubscriptionRoutesForUpdate(ctx context.Context, arg GetApplicableSubscriptionRoutesForUpdateParams) ([]GetApplicableSubscriptionRoutesForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getApplicableSubscriptionRoutesForUpdate, arg.UserID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApplicableSubscriptionRoutesForUpdateRow{}
	for rows.Next() {
		var i GetApplicableSubscriptionRoutesForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServicePlanVersionID,
			&i.Status,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.Notes,
			&i.AssignedBy,
			&i.SuspendedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.ResourcePoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentServicePlanVersion = `-- name: GetCurrentServicePlanVersion :one
SELECT version.id, version.service_plan_id, version.version, version.token_quota, version.validity_days, version.concurrency_limit, version.rpm_limit, version.tpm_limit, version.created_by, version.created_at FROM service_plans plan
JOIN service_plan_versions version ON version.id = plan.current_version_id
WHERE plan.id = $1 AND plan.status = 'active'
`

func (q *Queries) GetCurrentServicePlanVersion(ctx context.Context, servicePlanID uuid.UUID) (ServicePlanVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentServicePlanVersion, servicePlanID)
	var i ServicePlanVersion
	err := row.Scan(
		&i.ID,
		&i.ServicePlanID,
		&i.Version,
		&i.TokenQuota,
		&i.ValidityDays,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getServicePlan = `-- name: GetServicePlan :one
SELECT plan.id, plan.slug, plan.name, plan.description, plan.kind, plan.status, plan.current_version_id, plan.created_by, plan.created_at, plan.updated_at, version.version, version.token_quota, version.validity_days,
       version.concurrency_limit, version.rpm_limit, version.tpm_limit,
       version.created_by AS version_created_by, version.created_at AS version_created_at,
       (SELECT count(*) FROM service_plan_version_routes route WHERE route.service_plan_version_id = version.id) AS route_count
FROM service_plans plan
LEFT JOIN service_plan_versions version ON version.id = plan.current_version_id
WHERE plan.id = $1
`

type GetServicePlanRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Kind             PlanKind           `json:"kind"`
	Status           ServicePlanStatus  `json:"status"`
	CurrentVersionID *uuid.UUID         `json:"current_version_id"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Version          *int32             `json:"version"`
	TokenQuota       *int64             `json:"token_quota"`
	ValidityDays     *int32             `json:"validity_days"`
	ConcurrencyLimit *int32             `json:"concurrency_limit"`
	RpmLimit         *int32             `json:"rpm_limit"`
	TpmLimit         *int64             `json:"tpm_limit"`
	VersionCreatedBy *uuid.UUID         `json:"version_created_by"`
	VersionCreatedAt pgtype.Timestamptz `json:"version_created_at"`
	RouteCount       int64              `json:"route_count"`
}

func (q *Queries) GetServicePlan(ctx context.Context, id uuid.UUID) (GetServicePlanRow, error) {
	row := q.db.QueryRow(ctx, getServicePlan, id)
	var i GetServicePlanRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.TokenQuota,
		&i.ValidityDays,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.VersionCreatedBy,
		&i.VersionCreatedAt,
		&i.RouteCount,
	)
	return i, err
}

const getServicePlanForUpdate = `-- name: GetServicePlanForUpdate :one
SELECT id, slug, name, description, kind, status, current_version_id, created_by, created_at, updated_at FROM service_plans WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetServicePlanForUpdate(ctx context.Context, id uuid.UUID) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, getServicePlanForUpdate, id)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServicePlanMutation = `-- name: GetServicePlanMutation :one
SELECT id, actor_user_id, action, idempotency_key, request_fingerprint, request_id, service_plan_id, result, created_at FROM service_plan_mutations
WHERE actor_user_id = $1 AND action = $2 AND idempotency_key = $3
`

type GetServicePlanMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Action         string    `json:"action"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetServicePlanMutation(ctx context.Context, arg GetServicePlanMutationParams) (ServicePlanMutation, error) {
	row := q.db.QueryRow(ctx, getServicePlanMutation, arg.ActorUserID, arg.Action, arg.IdempotencyKey)
	var i ServicePlanMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.ServicePlanID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT subscription.id, subscription.user_id, subscription.service_plan_version_id, subscription.status, subscription.granted_tokens, subscription.starts_at, subscription.expires_at, subscription.notes, subscription.assigned_by, subscription.suspended_at, subscription.canceled_at, subscription.created_at, subscription.updated_at, plan.id AS service_plan_id, plan.name AS service_plan_name, plan.kind AS plan_kind,
       version.version AS plan_version, version.concurrency_limit, version.rpm_limit, version.tpm_limit,
       member.email AS member_email, member.display_name AS member_name,
       coalesce((SELECT sum(event.token_delta) FROM ledger_events event WHERE event.subscription_id = subscription.id), 0)::bigint AS balance_tokens
FROM subscriptions subscription
JOIN service_plan_versions version ON version.id = subscription.service_plan_version_id
JOIN service_plans plan ON plan.id = version.service_plan_id
JOIN users member ON member.id = subscription.user_id
WHERE subscription.id = $1
`

type GetSubscriptionRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	ServicePlanVersionID uuid.UUID          `json:"service_plan_version_id"`
	Status               SubscriptionStatus `json:"status"`
	GrantedTokens        int64              `json:"granted_tokens"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Notes                string             `json:"notes"`
	AssignedBy           uuid.UUID          `json:"assigned_by"`
	SuspendedAt          pgtype.Timestamptz `json:"suspended_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ServicePlanID        uuid.UUID          `json:"service_plan_id"`
	ServicePlanName      string             `json:"service_plan_name"`
	PlanKind             PlanKind           `json:"plan_kind"`
	PlanVersion          int32              `json:"plan_version"`
	ConcurrencyLimit     int32              `json:"concurrency_limit"`
	RpmLimit             *int32             `json:"rpm_limit"`
	TpmLimit             *int64             `json:"tpm_limit"`
	MemberEmail          string             `json:"member_email"`
	MemberName           string             `json:"member_name"`
	BalanceTokens        int64              `json:"balance_tokens"`
}

func (q *Queries) GetSubscription(ctx context.Context, id uuid.UUID) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServicePlanVersionID,
		&i.Status,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Notes,
		&i.AssignedBy,
		&i.SuspendedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServicePlanID,
		&i.ServicePlanName,
		&i.PlanKind,
		&i.PlanVersion,
		&i.ConcurrencyLimit,
		&i.RpmLimit,
		&i.TpmLimit,
		&i.MemberEmail,
		&i.MemberName,
		&i.BalanceTokens,
	)
	return i, err
}

const getSubscriptionForUpdate = `-- name: GetSubscriptionForUpdate :one
SELECT id, user_id, service_plan_version_id, status, granted_tokens, starts_at, expires_at, notes, assigned_by, suspended_at, canceled_at, created_at, updated_at FROM subscriptions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSubscriptionForUpdate(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForUpdate, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServicePlanVersionID,
		&i.Status,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Notes,
		&i.AssignedBy,
		&i.SuspendedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionMutation = `-- name: GetSubscriptionMutation :one
SELECT id, actor_user_id, action, idempotency_key, request_fingerprint, request_id, subscription_id, result, created_at FROM subscription_mutations
WHERE actor_user_id = $1 AND action = $2 AND idempotency_key = $3
`

type GetSubscriptionMutationParams struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Action         string    `json:"action"`
	IdempotencyKey uuid.UUID `json:"idempotency_key"`
}

func (q *Queries) GetSubscriptionMutation(ctx context.Context, arg GetSubscriptionMutationParams) (SubscriptionMutation, error) {
	row := q.db.QueryRow(ctx, getSubscriptionMutation, arg.ActorUserID, arg.Action, arg.IdempotencyKey)
	var i SubscriptionMutation
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.RequestID,
		&i.SubscriptionID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const listServicePlanVersionRoutes = `-- name: ListServicePlanVersionRoutes :many
SELECT route.service_plan_version_id, route.model_id, model.public_name AS model_name,
       route.resource_pool_id, pool.name AS resource_pool_name, pool.slug AS resource_pool_slug,
       provider.name AS provider_name
FROM service_plan_version_routes route
JOIN models model ON model.id = route.model_id
JOIN resource_pools pool ON pool.id = route.resource_pool_id
JOIN providers provider ON provider.id = pool.provider_id
WHERE route.service_plan_version_id = $1
ORDER BY model.public_name, pool.name, route.model_id
`

type ListServicePlanVersionRoutesRow struct {
	ServicePlanVersionID uuid.UUID `json:"service_plan_version_id"`
	ModelID              uuid.UUID `json:"model_id"`
	ModelName            string    `json:"model_name"`
	ResourcePoolID       uuid.UUID `json:"resource_pool_id"`
	ResourcePoolName     string    `json:"resource_pool_name"`
	ResourcePoolSlug     string    `json:"resource_pool_slug"`
	ProviderName         string    `json:"provider_name"`
}

func (q *Queries) ListServicePlanVersionRoutes(ctx context.Context, servicePlanVersionID uuid.UUID) ([]ListServicePlanVersionRoutesRow, error) {
	rows, err := q.db.Query(ctx, listServicePlanVersionRoutes, servicePlanVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicePlanVersionRoutesRow{}
	for rows.Next() {
		var i ListServicePlanVersionRoutesRow
		if err := rows.Scan(
			&i.ServicePlanVersionID,
			&i.ModelID,
			&i.ModelName,
			&i.ResourcePoolID,
			&i.ResourcePoolName,
			&i.ResourcePoolSlug,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePlans = `-- name: ListServicePlans :many
SELECT plan.id, plan.slug, plan.name, plan.description, plan.kind, plan.status, plan.current_version_id, plan.created_by, plan.created_at, plan.updated_at, version.version, version.token_quota, version.validity_days,
       version.concurrency_limit, version.rpm_limit, version.tpm_limit,
       version.created_by AS version_created_by, version.created_at AS version_created_at,
       (SELECT count(*) FROM service_plan_version_routes route WHERE route.service_plan_version_id = version.id) AS route_count,
       (SELECT count(*) FROM subscriptions subscription
        WHERE subscription.service_plan_version_id = version.id
          AND subscription.status IN ('scheduled', 'active')
          AND subscription.expires_at > now()) AS active_subscription_count
FROM service_plans plan
LEFT JOIN service_plan_versions version ON version.id = plan.current_version_id
WHERE ($1::boolean OR plan.status <> 'archived')
ORDER BY CASE plan.status WHEN 'active' THEN 0 WHEN 'disabled' THEN 1 ELSE 2 END, plan.name, plan.id
`

type ListServicePlansRow struct {
	ID                      uuid.UUID          `json:"id"`
	Slug                    string             `json:"slug"`
	Name                    string             `json:"name"`
	Description             string             `json:"description"`
	Kind                    PlanKind           `json:"kind"`
	Status                  ServicePlanStatus  `json:"status"`
	CurrentVersionID        *uuid.UUID         `json:"current_version_id"`
	CreatedBy               uuid.UUID          `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Version                 *int32             `json:"version"`
	TokenQuota              *int64             `json:"token_quota"`
	ValidityDays            *int32             `json:"validity_days"`
	ConcurrencyLimit        *int32             `json:"concurrency_limit"`
	RpmLimit                *int32             `json:"rpm_limit"`
	TpmLimit                *int64             `json:"tpm_limit"`
	VersionCreatedBy        *uuid.UUID         `json:"version_created_by"`
	VersionCreatedAt        pgtype.Timestamptz `json:"version_created_at"`
	RouteCount              int64              `json:"route_count"`
	ActiveSubscriptionCount int64              `json:"active_subscription_count"`
}

func (q *Queries) ListServicePlans(ctx context.Context, includeArchived bool) ([]ListServicePlansRow, error) {
	rows, err := q.db.Query(ctx, listServicePlans, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicePlansRow{}
	for rows.Next() {
		var i ListServicePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Status,
			&i.CurrentVersionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.TokenQuota,
			&i.ValidityDays,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.VersionCreatedBy,
			&i.VersionCreatedAt,
			&i.RouteCount,
			&i.ActiveSubscriptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT subscription.id, subscription.user_id, subscription.service_plan_version_id, subscription.status, subscription.granted_tokens, subscription.starts_at, subscription.expires_at, subscription.notes, subscription.assigned_by, subscription.suspended_at, subscription.canceled_at, subscription.created_at, subscription.updated_at, plan.id AS service_plan_id, plan.name AS service_plan_name, plan.kind AS plan_kind,
       version.version AS plan_version, version.concurrency_limit, version.rpm_limit, version.tpm_limit,
       member.email AS member_email, member.display_name AS member_name,
       coalesce((SELECT sum(event.token_delta) FROM ledger_events event WHERE event.subscription_id = subscription.id), 0)::bigint AS balance_tokens
FROM subscriptions subscription
JOIN service_plan_versions version ON version.id = subscription.service_plan_version_id
JOIN service_plans plan ON plan.id = version.service_plan_id
JOIN users member ON member.id = subscription.user_id
WHERE ($1::uuid IS NULL OR subscription.user_id = $1)
  AND ($2::text = '' OR concat_ws(' ', member.email, member.display_name, plan.name) ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR
       CASE
         WHEN subscription.status IN ('suspended', 'canceled') THEN subscription.status::text
         WHEN subscription.expires_at <= now() THEN 'expired'
         WHEN subscription.starts_at > now() THEN 'scheduled'
         ELSE 'active'
       END = $3::text)
ORDER BY subscription.created_at DESC, subscription.id
LIMIT $5 OFFSET $4
`

type ListSubscriptionsParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	Search     string     `json:"search"`
	Status     string     `json:"status"`
	PageOffset int32      `json:"page_offset"`
	PageSize   int32      `json:"page_size"`
}

type ListSubscriptionsRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	ServicePlanVersionID uuid.UUID          `json:"service_plan_version_id"`
	Status               SubscriptionStatus `json:"status"`
	GrantedTokens        int64              `json:"granted_tokens"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Notes                string             `json:"notes"`
	AssignedBy           uuid.UUID          `json:"assigned_by"`
	SuspendedAt          pgtype.Timestamptz `json:"suspended_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ServicePlanID        uuid.UUID          `json:"service_plan_id"`
	ServicePlanName      string             `json:"service_plan_name"`
	PlanKind             PlanKind           `json:"plan_kind"`
	PlanVersion          int32              `json:"plan_version"`
	ConcurrencyLimit     int32              `json:"concurrency_limit"`
	RpmLimit             *int32             `json:"rpm_limit"`
	TpmLimit             *int64             `json:"tpm_limit"`
	MemberEmail          string             `json:"member_email"`
	MemberName           string             `json:"member_name"`
	BalanceTokens        int64              `json:"balance_tokens"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.UserID,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsRow{}
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServicePlanVersionID,
			&i.Status,
			&i.GrantedTokens,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.Notes,
			&i.AssignedBy,
			&i.SuspendedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServicePlanID,
			&i.ServicePlanName,
			&i.PlanKind,
			&i.PlanVersion,
			&i.ConcurrencyLimit,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.MemberEmail,
			&i.MemberName,
			&i.BalanceTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextServicePlanVersion = `-- name: NextServicePlanVersion :one
SELECT (coalesce(max(version), 0) + 1)::integer AS version
FROM service_plan_versions WHERE service_plan_id = $1
`

func (q *Queries) NextServicePlanVersion(ctx context.Context, servicePlanID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextServicePlanVersion, servicePlanID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const publishServicePlanVersion = `-- name: PublishServicePlanVersion :one
UPDATE service_plans
SET name = $1, description = $2, kind = $3,
    status = 'active', current_version_id = $4, updated_at = now()
WHERE id = $5 RETURNING id, slug, name, description, kind, status, current_version_id, created_by, created_at, updated_at
`

type PublishServicePlanVersionParams struct {
	Name             string     `json:"name"`
	Description      string     `json:"description"`
	Kind             PlanKind   `json:"kind"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
	ID               uuid.UUID  `json:"id"`
}

func (q *Queries) PublishServicePlanVersion(ctx context.Context, arg PublishServicePlanVersionParams) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, publishServicePlanVersion,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.CurrentVersionID,
		arg.ID,
	)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setServicePlanStatus = `-- name: SetServicePlanStatus :one
UPDATE service_plans SET status = $1, updated_at = now()
WHERE id = $2 AND status <> 'archived' RETURNING id, slug, name, description, kind, status, current_version_id, created_by, created_at, updated_at
`

type SetServicePlanStatusParams struct {
	Status ServicePlanStatus `json:"status"`
	ID     uuid.UUID         `json:"id"`
}

func (q *Queries) SetServicePlanStatus(ctx context.Context, arg SetServicePlanStatusParams) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, setServicePlanStatus, arg.Status, arg.ID)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = $1,
    suspended_at = CASE WHEN $1::subscription_status = 'suspended' THEN now() ELSE NULL END,
    canceled_at = CASE WHEN $1::subscription_status = 'canceled' THEN now() ELSE NULL END,
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE id = $2 AND status <> 'canceled' AND updated_at = $3
RETURNING id, user_id, service_plan_version_id, status, granted_tokens, starts_at, expires_at, notes, assigned_by, suspended_at, canceled_at, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	Status            SubscriptionStatus `json:"status"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.Status, arg.ID, arg.ExpectedUpdatedAt)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServicePlanVersionID,
		&i.Status,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Notes,
		&i.AssignedBy,
		&i.SuspendedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionTerm = `-- name: UpdateSubscriptionTerm :one
UPDATE subscriptions
SET granted_tokens = $1, starts_at = $2, expires_at = $3,
    notes = $4,
    status = $5, suspended_at = NULL, canceled_at = NULL,
    updated_at = GREATEST(clock_timestamp(), updated_at + interval '1 microsecond')
WHERE id = $6 AND status <> 'canceled' AND updated_at = $7
RETURNING id, user_id, service_plan_version_id, status, granted_tokens, starts_at, expires_at, notes, assigned_by, suspended_at, canceled_at, created_at, updated_at
`

type UpdateSubscriptionTermParams struct {
	GrantedTokens     int64              `json:"granted_tokens"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Notes             string             `json:"notes"`
	Status            SubscriptionStatus `json:"status"`
	ID                uuid.UUID          `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) UpdateSubscriptionTerm(ctx context.Context, arg UpdateSubscriptionTermParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionTerm,
		arg.GrantedTokens,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.Notes,
		arg.Status,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServicePlanVersionID,
		&i.Status,
		&i.GrantedTokens,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.Notes,
		&i.AssignedBy,
		&i.SuspendedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
