FROM docker@sha256:0135662b510037ea581d99c2e5929c5e01185139c0b86986a418bd4da0b98a44 AS docker_cli

FROM bash@sha256:3bee76a96d86d5d2d5efc7c1c570e5a7c95db22348a26944e0e546fa174e3324
RUN apk add --no-cache \
    coreutils=9.7-r1 \
    findutils=4.10.0-r0 \
    util-linux=2.41-r9
COPY --from=docker_cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker_cli /usr/local/libexec/docker/cli-plugins/docker-compose /usr/local/libexec/docker/cli-plugins/docker-compose
ENTRYPOINT ["bash", "-lc"]
